"""
GoFish Graphics in Python
"""

from .ast import (
    chart,
    ChartBuilder,
    mark,
    create_name,
    Token,
    LayerBuilder,
    layer,
    enclose,
    background,
    position,
    Constraint,
    Schema,
    ColumnSchema,
    Calendar,
    CalendarPartition,
    ref,
    arrow,
    over,
    intersect,
    exclude,
    subtract,
    paint,
    mask,
    cut,
    offset,
    spread,
    stack,
    derive,
    compose,
    resolve,
    join,
    filter,
    group,
    scatter,
    treemap,
    pack,
    partition,
    table,
    log,
    select_all,
    assign_gradient_color,
    normalize,
    repeat,
    rect,
    circle,
    line,
    ribbon,
    blank,
    region,
    ellipse,
    petal,
    text,
    image,
    polygon,
    datum,
    field,
)
from .datum_projection import pluck
from .charts import bar_chart

# Strategy families (#1013): one module per family, with a lowercase file
# name, bound here under its capitalized name. `Curve.monotone` and
# `from gofish.curve import monotone` are the same function.
from . import color as Color
from . import coord as Coord
from . import curve as Curve
from . import overlap as Overlap
from . import tile as Tile

__all__ = [
    "chart",
    "ChartBuilder",
    "mark",
    "create_name",
    "Token",
    "LayerBuilder",
    "layer",
    "enclose",
    "background",
    "position",
    "Constraint",
    "Schema",
    "ColumnSchema",
    "Calendar",
    "CalendarPartition",
    "ref",
    "arrow",
    "over",
    "intersect",
    "exclude",
    "subtract",
    "paint",
    "mask",
    "cut",
    "offset",
    "spread",
    "stack",
    "derive",
    "compose",
    "resolve",
    "join",
    "filter",
    "group",
    "scatter",
    "treemap",
    "pack",
    "partition",
    "table",
    "log",
    "select_all",
    "assign_gradient_color",
    "normalize",
    "repeat",
    "rect",
    "circle",
    "line",
    "ribbon",
    "blank",
    "region",
    "ellipse",
    "petal",
    "text",
    "image",
    "polygon",
    "datum",
    "field",
    "pluck",
    "bar_chart",
    "Color",
    "Coord",
    "Curve",
    "Overlap",
    "Tile",
]

__version__ = "0.1.0"
