# GENERATED by packages/gofish-python/scripts/generate.ts from gofish-ir
# descriptors — do not edit; run `pnpm --filter gofish-python gen`.
"""Mechanical factory layer generated from the gofish-ir frontend descriptor
table (packages/gofish-ir/src/frontend/descriptors.ts). See
apps/docs/docs/internals/design/python-wrapper-codegen.md.

`gofish/ast.py` imports from here for the constructs whose Python body is
pure kwargs-collection + wire-key rename; dispatch logic (dual-form
operator-vs-combinator, ref-shape narrowing, DataFrame conversion, the
lambda/RPC bridge) stays hand-written there.
"""

from typing import Any, Dict, List, Optional, Union

from .ast import Mark, _channel


# --- Leaf marks -------------------------------------------------------------

def rect(*, debug: Optional[bool] = None, x: Optional[Union[int, float, str]] = None, cx: Optional[Union[int, float, str]] = None, x2: Optional[Union[int, float, str]] = None, w: Optional[Union[int, float, str]] = None, emX: Optional[bool] = None, y: Optional[Union[int, float, str]] = None, cy: Optional[Union[int, float, str]] = None, y2: Optional[Union[int, float, str]] = None, h: Optional[Union[int, float, str]] = None, emY: Optional[bool] = None, dims: Optional[Any] = None, fill: Optional[str] = None, stroke: Optional[str] = None, strokeWidth: Optional[float] = None, opacity: Optional[float] = None, filter: Optional[str] = None, key: Optional[str] = None, rx: Optional[float] = None, ry: Optional[float] = None, aspectRatio: Optional[float] = None) -> Mark:
    """A rectangle. Box geometry via the shared dims channels.

    Args:
        debug: Dev-only flag: logs this mark's key and datum to the console as it is built. It changes nothing about what is drawn.
        x: Left edge position.
        cx: Center x.
        x2: Right edge position.
        w: Width.
        emX: Embed x in the parent's x space.
        y: Top/bottom edge position (y-up: bottom).
        cy: Center y.
        y2: Other y edge position.
        h: Height.
        emY: Embed y in the parent's y space.
        dims: Box dimensions by axis name: x/y, or a name the enclosing coordinate space declares (polar theta/r, geo lon/lat). Each value is a position (like x) or an interval {min, center, max, size, embedded}.
        fill: Fill color, or a field name for a color scale.
        stroke: Stroke color. Defaults to `fill`.
        strokeWidth: Stroke width in pixels. Default 0.
        opacity: Opacity, 0 to 1. Default 1.
        filter: Raw SVG filter attribute.
        key: Internal per-node key override.
        rx: Corner radius, x. Default 0.
        ry: Corner radius, y. Default 0.
        aspectRatio: w/h ratio to enforce; the constraining axis wins when both are data-driven.
    """
    _kw: Dict[str, Any] = {}
    for _k, _v in [
        ("debug", debug),
        ("x", x),
        ("cx", cx),
        ("x2", x2),
        ("w", w),
        ("emX", emX),
        ("y", y),
        ("cy", cy),
        ("y2", y2),
        ("h", h),
        ("emY", emY),
        ("dims", dims),
        ("fill", fill),
        ("stroke", stroke),
        ("strokeWidth", strokeWidth),
        ("opacity", opacity),
        ("filter", filter),
        ("key", key),
        ("rx", rx),
        ("ry", ry),
        ("aspectRatio", aspectRatio),
    ]:
        if _v is not None:
            _kw[_k] = _channel(_v)
    return Mark("rect", **_kw)

def circle(*, debug: Optional[bool] = None, r: Optional[Union[int, float, str]] = None, fill: Optional[str] = None, stroke: Optional[str] = None, strokeWidth: Optional[float] = None, opacity: Optional[float] = None, **kwargs: Any) -> Mark:
    """A circle, drawn as an aspect-locked ellipse. Does NOT support the boxDims positioning channels directly (JS `circle()` in marks/chart.ts destructures only r/fill/stroke/strokeWidth/opacity) — position it via `spread`/`scatter`.

    Args:
        debug: Dev-only flag: logs this mark's key and datum to the console as it is built. It changes nothing about what is drawn.
        r: Radius; becomes w=h=2r on the underlying ellipse.
        fill: Fill color, or a field name for a color scale.
        stroke: Stroke color. Defaults to `fill`.
        strokeWidth: Stroke width in pixels. Default 0.
        opacity: Opacity, 0 to 1, applied to fill and stroke. In JS it may also be a per-datum accessor or a `live(...)` value; only a literal number crosses the wire. Default 1.
    """
    _kw: Dict[str, Any] = {}
    for _k, _v in [
        ("debug", debug),
        ("r", r),
        ("fill", fill),
        ("stroke", stroke),
        ("strokeWidth", strokeWidth),
        ("opacity", opacity),
    ]:
        if _v is not None:
            _kw[_k] = _channel(_v)
    for _k, _v in kwargs.items():
        if _v is not None:
            _kw[_k] = _channel(_v)
    return Mark("circle", **_kw)

def ellipse(*, debug: Optional[bool] = None, x: Optional[Union[int, float, str]] = None, cx: Optional[Union[int, float, str]] = None, x2: Optional[Union[int, float, str]] = None, w: Optional[Union[int, float, str]] = None, emX: Optional[bool] = None, y: Optional[Union[int, float, str]] = None, cy: Optional[Union[int, float, str]] = None, y2: Optional[Union[int, float, str]] = None, h: Optional[Union[int, float, str]] = None, emY: Optional[bool] = None, dims: Optional[Any] = None, fill: Optional[str] = None, stroke: Optional[str] = None, strokeWidth: Optional[float] = None, opacity: Optional[float] = None, aspectRatio: Optional[float] = None, **kwargs: Any) -> Mark:
    """An ellipse. Box geometry via the shared dims channels; paint is a strict subset of `paint` (no filter).

    Args:
        debug: Dev-only flag: logs this mark's key and datum to the console as it is built. It changes nothing about what is drawn.
        x: Left edge position.
        cx: Center x.
        x2: Right edge position.
        w: Width.
        emX: Embed x in the parent's x space.
        y: Top/bottom edge position (y-up: bottom).
        cy: Center y.
        y2: Other y edge position.
        h: Height.
        emY: Embed y in the parent's y space.
        dims: Box dimensions by axis name: x/y, or a name the enclosing coordinate space declares (polar theta/r, geo lon/lat). Each value is a position (like x) or an interval {min, center, max, size, embedded}.
        fill: Fill color, or a field name for a color scale.
        stroke: Stroke color. Defaults to `fill`.
        strokeWidth: Stroke width in pixels. Default 0.
        opacity: Opacity, 0 to 1. Default 1.
        aspectRatio: w/h ratio to enforce. When both dims are data-driven, the constraining axis is used.
    """
    _kw: Dict[str, Any] = {}
    for _k, _v in [
        ("debug", debug),
        ("x", x),
        ("cx", cx),
        ("x2", x2),
        ("w", w),
        ("emX", emX),
        ("y", y),
        ("cy", cy),
        ("y2", y2),
        ("h", h),
        ("emY", emY),
        ("dims", dims),
        ("fill", fill),
        ("stroke", stroke),
        ("strokeWidth", strokeWidth),
        ("opacity", opacity),
        ("aspectRatio", aspectRatio),
    ]:
        if _v is not None:
            _kw[_k] = _channel(_v)
    for _k, _v in kwargs.items():
        if _v is not None:
            _kw[_k] = _channel(_v)
    return Mark("ellipse", **_kw)

def petal(*, debug: Optional[bool] = None, x: Optional[Union[int, float, str]] = None, cx: Optional[Union[int, float, str]] = None, x2: Optional[Union[int, float, str]] = None, w: Optional[Union[int, float, str]] = None, emX: Optional[bool] = None, y: Optional[Union[int, float, str]] = None, cy: Optional[Union[int, float, str]] = None, y2: Optional[Union[int, float, str]] = None, h: Optional[Union[int, float, str]] = None, emY: Optional[bool] = None, dims: Optional[Any] = None, fill: Optional[str] = None, stroke: Optional[str] = None, strokeWidth: Optional[float] = None, **kwargs: Any) -> Mark:
    """A polar-only wedge/petal shape (Petal.tsx). Box geometry via the shared dims channels.

    Args:
        debug: Dev-only flag: logs this mark's key and datum to the console as it is built. It changes nothing about what is drawn.
        x: Left edge position.
        cx: Center x.
        x2: Right edge position.
        w: Width.
        emX: Embed x in the parent's x space.
        y: Top/bottom edge position (y-up: bottom).
        cy: Center y.
        y2: Other y edge position.
        h: Height.
        emY: Embed y in the parent's y space.
        dims: Box dimensions by axis name: x/y, or a name the enclosing coordinate space declares (polar theta/r, geo lon/lat). Each value is a position (like x) or an interval {min, center, max, size, embedded}.
        fill: Fill color, or a field name for a color scale.
        stroke: Stroke color. Defaults to `fill`.
        strokeWidth: Stroke width in pixels. Default 0.
    """
    _kw: Dict[str, Any] = {}
    for _k, _v in [
        ("debug", debug),
        ("x", x),
        ("cx", cx),
        ("x2", x2),
        ("w", w),
        ("emX", emX),
        ("y", y),
        ("cy", cy),
        ("y2", y2),
        ("h", h),
        ("emY", emY),
        ("dims", dims),
        ("fill", fill),
        ("stroke", stroke),
        ("strokeWidth", strokeWidth),
    ]:
        if _v is not None:
            _kw[_k] = _channel(_v)
    for _k, _v in kwargs.items():
        if _v is not None:
            _kw[_k] = _channel(_v)
    return Mark("petal", **_kw)

def text(*, debug: Optional[bool] = None, x: Optional[Union[int, float, str]] = None, cx: Optional[Union[int, float, str]] = None, x2: Optional[Union[int, float, str]] = None, w: Optional[Union[int, float, str]] = None, emX: Optional[bool] = None, y: Optional[Union[int, float, str]] = None, cy: Optional[Union[int, float, str]] = None, y2: Optional[Union[int, float, str]] = None, h: Optional[Union[int, float, str]] = None, emY: Optional[bool] = None, dims: Optional[Any] = None, key: Optional[str] = None, text: str, fill: Optional[str] = None, stroke: Optional[str] = None, strokeWidth: Optional[float] = None, filter: Optional[str] = None, fontSize: Optional[float] = None, fontFamily: Optional[str] = None, fontStyle: Optional[str] = None, fontWeight: Optional[Union[float, str]] = None, debugBoundingBox: Optional[bool] = None, rotate: Optional[float] = None, textAnchor: Optional[str] = None) -> Mark:
    """A text label. Box geometry via the shared dims channels positions the text anchor.

    Args:
        debug: Dev-only flag: on the shape marks (rect, circle, ellipse, petal, text, image, polygon, blank) it logs the mark's key and datum to the console as the mark is built. It changes nothing about what is drawn; the connector marks accept it and ignore it.
        x: Left edge position.
        cx: Center x.
        x2: Right edge position.
        w: Width.
        emX: Embed x in the parent's x space.
        y: Top/bottom edge position (y-up: bottom).
        cy: Center y.
        y2: Other y edge position.
        h: Height.
        emY: Embed y in the parent's y space.
        dims: Box dimensions by axis name: x/y, or a name the enclosing coordinate space declares (polar theta/r, geo lon/lat). Each value is a position (like x) or an interval {min, center, max, size, embedded}.
        key: Internal per-node key override.
        text: Text content (raw channel — a literal, field name, or accessor).
        fill: Fill color, or a field name for a color scale. Default "black".
        stroke: Stroke color.
        strokeWidth: Stroke width in pixels. Default 0.
        filter: Raw SVG filter attribute.
        fontSize: Font size in pixels. Default 12.
        fontFamily: Font family. Default "system-ui, sans-serif".
        fontStyle: Raw CSS font-style (e.g. "italic").
        fontWeight: CSS font-weight (e.g. 300, 700, "bold").
        debugBoundingBox: Draw the text's bounding box, for layout debugging. Default false.
        rotate: Rotation in degrees, applied in the chart's y-up world frame about the text anchor. Default 0.
        textAnchor: Where the text anchor — the local origin `rotate` pivots about and dims channels position — sits along the string: its first character, center, or last character. Default "start".
    """
    _kw: Dict[str, Any] = {}
    for _k, _v in [
        ("debug", debug),
        ("x", x),
        ("cx", cx),
        ("x2", x2),
        ("w", w),
        ("emX", emX),
        ("y", y),
        ("cy", cy),
        ("y2", y2),
        ("h", h),
        ("emY", emY),
        ("dims", dims),
        ("key", key),
        ("text", text),
        ("fill", fill),
        ("stroke", stroke),
        ("strokeWidth", strokeWidth),
        ("filter", filter),
        ("fontSize", fontSize),
        ("fontFamily", fontFamily),
        ("fontStyle", fontStyle),
        ("fontWeight", fontWeight),
        ("debugBoundingBox", debugBoundingBox),
        ("rotate", rotate),
        ("textAnchor", textAnchor),
    ]:
        if _v is not None:
            _kw[_k] = _channel(_v)
    return Mark("text", **_kw)

def image(*, debug: Optional[bool] = None, x: Optional[Union[int, float, str]] = None, cx: Optional[Union[int, float, str]] = None, x2: Optional[Union[int, float, str]] = None, w: Optional[Union[int, float, str]] = None, emX: Optional[bool] = None, y: Optional[Union[int, float, str]] = None, cy: Optional[Union[int, float, str]] = None, y2: Optional[Union[int, float, str]] = None, h: Optional[Union[int, float, str]] = None, emY: Optional[bool] = None, dims: Optional[Any] = None, key: Optional[str] = None, href: str, filter: Optional[str] = None, opacity: Optional[float] = None, preserveAspectRatio: Optional[str] = None) -> Mark:
    """An embedded raster/SVG image. Box geometry via the shared dims channels.

    Args:
        debug: Dev-only flag: logs this mark's key and datum to the console as it is built. It changes nothing about what is drawn.
        x: Left edge position.
        cx: Center x.
        x2: Right edge position.
        w: Width.
        emX: Embed x in the parent's x space.
        y: Top/bottom edge position (y-up: bottom).
        cy: Center y.
        y2: Other y edge position.
        h: Height.
        emY: Embed y in the parent's y space.
        dims: Box dimensions by axis name: x/y, or a name the enclosing coordinate space declares (polar theta/r, geo lon/lat). Each value is a position (like x) or an interval {min, center, max, size, embedded}.
        key: Internal per-node key override.
        href: Image URL or data URI.
        filter: Raw SVG filter attribute.
        opacity: Opacity, 0 to 1.
        preserveAspectRatio: Raw SVG preserveAspectRatio value. Default "xMidYMid meet".
    """
    _kw: Dict[str, Any] = {}
    for _k, _v in [
        ("debug", debug),
        ("x", x),
        ("cx", cx),
        ("x2", x2),
        ("w", w),
        ("emX", emX),
        ("y", y),
        ("cy", cy),
        ("y2", y2),
        ("h", h),
        ("emY", emY),
        ("dims", dims),
        ("key", key),
        ("href", href),
        ("filter", filter),
        ("opacity", opacity),
        ("preserveAspectRatio", preserveAspectRatio),
    ]:
        if _v is not None:
            _kw[_k] = _channel(_v)
    return Mark("image", **_kw)

def polygon(*, debug: Optional[bool] = None, points: Any, fill: Optional[str] = None, stroke: Optional[str] = None, strokeWidth: Optional[float] = None, opacity: Optional[float] = None) -> Mark:
    """A closed polygon defined by local-coordinate points (y-up), given literally or read from a field. No dims channels — the bbox is computed from `points`.

    Args:
        debug: Dev-only flag: logs this mark's key and datum to the console as it is built. It changes nothing about what is drawn.
        points: Vertex list, at least 3 points — either a literal ring, or the name of a field holding one ring per row (which is how one mark draws a whole basemap).
        fill: Fill color. Default "black".
        stroke: Stroke color. Defaults to `fill`.
        strokeWidth: Stroke width in pixels. Default 0.
        opacity: Opacity, 0 to 1, applied to both fill and stroke. Default 1.
    """
    _kw: Dict[str, Any] = {}
    for _k, _v in [
        ("debug", debug),
        ("points", points),
        ("fill", fill),
        ("stroke", stroke),
        ("strokeWidth", strokeWidth),
        ("opacity", opacity),
    ]:
        if _v is not None:
            _kw[_k] = _channel(_v)
    return Mark("polygon", **_kw)

def blank(*, debug: Optional[bool] = None, emX: Optional[bool] = None, emY: Optional[bool] = None, w: Optional[Union[int, float, str]] = None, h: Optional[Union[int, float, str]] = None, fill: Optional[str] = None, **kwargs: Any) -> Mark:
    """An invisible sizing/positioning guide — a rect that emits no display items at all, with a restricted channel set (no x/y/cx/cy/x2/y2/theta/r — position it via a layout operator).

    Args:
        debug: Dev-only flag: logs this mark's key and datum to the console as it is built. It changes nothing about what is drawn.
        emX: Embed x in the parent's x space.
        emY: Embed y in the parent's y space.
        w: Width. Default 0.
        h: Height. Default 0.
        fill: Fill color. A blank never paints; `fill` only seeds the shared color scale.
    """
    _kw: Dict[str, Any] = {}
    for _k, _v in [
        ("debug", debug),
        ("emX", emX),
        ("emY", emY),
        ("w", w),
        ("h", h),
        ("fill", fill),
    ]:
        if _v is not None:
            _kw[_k] = _channel(_v)
    for _k, _v in kwargs.items():
        if _v is not None:
            _kw[_k] = _channel(_v)
    return Mark("blank", **_kw)


# --- Combinator-only marks ---------------------------------------------------

def over(children: List["Mark"], *, blendMode: Optional[str] = None) -> Mark:
    """Internal-only A ∪ B union compositing (not exported from lib.ts — use `layer`). Kept only so the deserializer can dispatch the wire type.

    Args:
        blendMode: Blend used where the two regions combine. Default "color".
    """
    kwargs: Dict[str, Any] = {}
    for _k, _v in [
        ("blendMode", blendMode),
    ]:
        if _v is not None:
            kwargs[_k] = _v
    return Mark("over", _children=list(children), **kwargs)

def intersect(children: List["Mark"], *, blendMode: Optional[str] = None) -> Mark:
    """Draw only where both regions overlap: A ∩ B. Binary only.

    Args:
        blendMode: Blend used where the two regions combine. Default "color".
    """
    kwargs: Dict[str, Any] = {}
    for _k, _v in [
        ("blendMode", blendMode),
    ]:
        if _v is not None:
            kwargs[_k] = _v
    return Mark("inside", _children=list(children), **kwargs)

def exclude(children: List["Mark"], *, blendMode: Optional[str] = None) -> Mark:
    """Symmetric difference (odd-overlap parity): A ^ B. Binary only.

    Args:
        blendMode: Blend used where the two regions combine. Default "color".
    """
    kwargs: Dict[str, Any] = {}
    for _k, _v in [
        ("blendMode", blendMode),
    ]:
        if _v is not None:
            kwargs[_k] = _v
    return Mark("xor", _children=list(children), **kwargs)

def subtract(children: List["Mark"], *, blendMode: Optional[str] = None) -> Mark:
    """Draw A with B removed: A − B. Binary only.

    Args:
        blendMode: Blend used where the two regions combine. Default "color".
    """
    kwargs: Dict[str, Any] = {}
    for _k, _v in [
        ("blendMode", blendMode),
    ]:
        if _v is not None:
            kwargs[_k] = _v
    return Mark("out", _children=list(children), **kwargs)

def paint(children: List["Mark"], *, blendMode: Optional[str] = None) -> Mark:
    """A is a base surface B is painted onto, clipped to A: A ∪ (B ∩ A). Result sized to A. Binary only.

    Args:
        blendMode: Blend used where the two regions combine. Default "color".
    """
    kwargs: Dict[str, Any] = {}
    for _k, _v in [
        ("blendMode", blendMode),
    ]:
        if _v is not None:
            kwargs[_k] = _v
    return Mark("atop", _children=list(children), **kwargs)

def mask(children: List["Mark"]) -> Mark:
    """Use A's region as a clip and paint B inside it without drawing A itself: B ∩ A, reporting A's bounds. Binary only. No options.
    """
    return Mark("mask", _children=list(children))

def enclose(children: List["Mark"], *, padding: Optional[float] = None, rx: Optional[float] = None, ry: Optional[float] = None, fill: Optional[str] = None, stroke: Optional[str] = None, strokeWidth: Optional[float] = None, strokeDasharray: Optional[str] = None, opacity: Optional[float] = None) -> Mark:
    """Draw a rounded-rect enclosure around the union of the children's bboxes, padded by `padding`.

    Args:
        padding: Pixels of slack between the children's bbox union and the drawn enclosure. Default 2.
        rx: Corner radius, x. Default 2.
        ry: Corner radius, y. Default 2.
        fill: Fill color of the enclosure. Default "none".
        stroke: Stroke color of the enclosure. Default "#D1D9E2".
        strokeWidth: Stroke width in pixels. Default 1.
        strokeDasharray: Raw SVG stroke-dasharray (e.g. "4 2") for a dashed enclosure.
        opacity: Opacity, 0 to 1. Default 1.
    """
    kwargs: Dict[str, Any] = {}
    for _k, _v in [
        ("padding", padding),
        ("rx", rx),
        ("ry", ry),
        ("fill", fill),
        ("stroke", stroke),
        ("strokeWidth", strokeWidth),
        ("strokeDasharray", strokeDasharray),
        ("opacity", opacity),
    ]:
        if _v is not None:
            kwargs[_k] = _v
    return Mark("enclose", _children=list(children), **kwargs)

def position(children: List["Mark"], *, key: Optional[str] = None, x: Optional[Union[int, float, str]] = None, y: Optional[Union[int, float, str]] = None) -> Mark:
    """Set a single child's min-corner (x, y) in parent coordinates — an absolute-offset placement primitive, NOT center-anchored. Unlike `enclose`'s convex-hull styling, `position` draws nothing of its own; it exists for cases (e.g. the Topology story's combinator trees) that need to place one child precisely without `enclose`'s fill/stroke/hull limits.

    Args:
        key: Internal per-node key override.
        x: Min-corner x offset.
        y: Min-corner y offset.
    """
    kwargs: Dict[str, Any] = {}
    for _k, _v in [
        ("key", key),
        ("x", x),
        ("y", y),
    ]:
        if _v is not None:
            kwargs[_k] = _v
    return Mark("position", _children=list(children), **kwargs)

def arrow(children: List["Mark"], *, bow: Optional[float] = None, stretch: Optional[float] = None, stretchMin: Optional[float] = None, stretchMax: Optional[float] = None, padStart: Optional[float] = None, padEnd: Optional[float] = None, flip: Optional[bool] = None, straights: Optional[bool] = None, stroke: Optional[str] = None, strokeWidth: Optional[float] = None, start: Optional[bool] = None) -> Mark:
    """A perfect-arrows box-to-box arrow between exactly two children.

    Args:
        bow: Baseline curvature. 0 is a straight line; higher values bow the arc further from center. Default 0.2.
        stretch: How much the bow grows as the endpoints get closer, and shrinks as they get farther apart. Default 0.5.
        stretchMin: Distance in pixels below which stretch has its full effect. Default 40.
        stretchMax: Distance in pixels above which stretch has no effect. Default 420.
        padStart: Gap in pixels between the source box and the start of the line. Default 5.
        padEnd: Gap in pixels between the end of the line and the target box, leaving room for the arrowhead. Default 20.
        flip: Flip which side the arrow bows toward. Default false.
        straights: Allow a perfectly straight line when the endpoints are axis-aligned, instead of forcing a slight bow. Default true.
        stroke: Color of the arrow's line and head, and of the start dot when shown. Default "black".
        strokeWidth: Line width; also scales the arrowhead and the start dot. Default 3.
        start: Draw a dot at the start endpoint. Default false.
    """
    kwargs: Dict[str, Any] = {}
    for _k, _v in [
        ("bow", bow),
        ("stretch", stretch),
        ("stretchMin", stretchMin),
        ("stretchMax", stretchMax),
        ("padStart", padStart),
        ("padEnd", padEnd),
        ("flip", flip),
        ("straights", straights),
        ("stroke", stroke),
        ("strokeWidth", strokeWidth),
        ("start", start),
    ]:
        if _v is not None:
            kwargs[_k] = _v
    return Mark("arrow", _children=list(children), **kwargs)


# --- Dual-form cores (dispatch stays hand-written in ast.py) -----------------

def _spread_opts(*, by: Optional[Any] = None, dir: Optional[str] = None, spacing: Optional[float] = None, alignment: Optional[str] = None, sharedScale: Optional[bool] = None, anchor: Optional[str] = None, reverse: Optional[bool] = None, glue: Optional[bool] = None, axes: Optional[Any] = None, w: Optional[Union[int, float, str]] = None, h: Optional[Union[int, float, str]] = None, size: Optional[Union[int, float, str]] = None, debug: Optional[bool] = None) -> Dict[str, Any]:
    """Arrange children along `dir` with spacing, aligning them on the cross axis.

    Args:
        by: Field to partition rows by; also accepts a field(...) accessor carrying domain ops (sort/reverse/bin).
        dir: Axis to spread along: x, y, or an axis name the enclosing coordinate space declares (polar theta/r, geo lon/lat).
        spacing: Gap between children, px. Default 8.
        alignment: Cross-axis alignment ("start" | "middle" | "end" | "baseline"). Default "baseline".
        sharedScale: Share one scale across all children. Default false.
        anchor: Whether spacing is measured between facing edges (edge), or as a fixed pitch between the named anchor point on each child. Default "edge".
        reverse: Reverse the children's order along dir. Default false.
        glue: Stack semantics: children glued, sizes sum; spacing forced to 0. Default false.
        w: Data-driven cross-axis extent (field/datum-sized children).
        h: Data-driven cross-axis extent (field/datum-sized children).
        size: Per-entry stack-axis extent (field/datum-sized children); a field(...).normalize() accessor makes it a space-filling spine.
        debug: Dev-only flag every operator accepts and currently ignores — it is dropped before layout. Use the `log` operator to print the rows at a point in the flow.
    """
    opts: Dict[str, Any] = {}
    for _k, _v in [
        ("by", by),
        ("dir", dir),
        ("spacing", spacing),
        ("alignment", alignment),
        ("sharedScale", sharedScale),
        ("anchor", anchor),
        ("reverse", reverse),
        ("glue", glue),
        ("axes", axes),
        ("w", w),
        ("h", h),
        ("size", size),
        ("debug", debug),
    ]:
        if _v is not None:
            opts[_k] = _v
    return opts

def _stack_opts(*, by: Optional[Any] = None, dir: Optional[str] = None, spacing: Optional[float] = None, glue: Optional[bool] = None, alignment: Optional[str] = None, sharedScale: Optional[bool] = None, anchor: Optional[str] = None, reverse: Optional[bool] = None, axes: Optional[Any] = None, w: Optional[Union[int, float, str]] = None, h: Optional[Union[int, float, str]] = None, size: Optional[Union[int, float, str]] = None, debug: Optional[bool] = None) -> Dict[str, Any]:
    """`spread({ glue: true })` under its own wire tag — children glued together (touching, no gaps).

    Args:
        by: Field to partition rows by; also accepts a field(...) accessor carrying domain ops (sort/reverse/bin).
        dir: Axis to stack along: x, y, or an axis name the enclosing coordinate space declares (polar theta/r, geo lon/lat).
        spacing: Forwarded to the underlying spread. Glue semantics force the effective gap to 0; accepted for spread-parity.
        glue: Spread-parity passthrough; stack always glues regardless.
        alignment: Cross-axis alignment ("start" | "middle" | "end" | "baseline"). Default "baseline".
        sharedScale: Share one scale across all children. Default false.
        anchor: Whether spacing is measured between facing edges (edge), or as a fixed pitch between the named anchor point on each child. Default "edge".
        reverse: Reverse the children's order along dir. Default false.
        w: Data-driven cross-axis extent (field/datum-sized children).
        h: Data-driven cross-axis extent (field/datum-sized children).
        size: Per-entry stack-axis extent (field/datum-sized children); a field(...).normalize() accessor makes it a space-filling spine.
        debug: Dev-only flag every operator accepts and currently ignores — it is dropped before layout. Use the `log` operator to print the rows at a point in the flow.
    """
    opts: Dict[str, Any] = {}
    for _k, _v in [
        ("by", by),
        ("dir", dir),
        ("spacing", spacing),
        ("glue", glue),
        ("alignment", alignment),
        ("sharedScale", sharedScale),
        ("anchor", anchor),
        ("reverse", reverse),
        ("axes", axes),
        ("w", w),
        ("h", h),
        ("size", size),
        ("debug", debug),
    ]:
        if _v is not None:
            opts[_k] = _v
    return opts

def _scatter_opts(*, by: Optional[Any] = None, x: Optional[Union[int, float, str]] = None, y: Optional[Union[int, float, str]] = None, xMin: Optional[Union[int, float, str]] = None, xMax: Optional[Union[int, float, str]] = None, yMin: Optional[Union[int, float, str]] = None, yMax: Optional[Union[int, float, str]] = None, dims: Optional[Any] = None, alignment: Optional[str] = None, axes: Optional[Any] = None, w: Optional[Union[int, float, str]] = None, h: Optional[Union[int, float, str]] = None, debug: Optional[bool] = None) -> Dict[str, Any]:
    """Position each child at an explicit (x, y) point or [min, max] span in data space.

    Args:
        by: Field to partition rows by; also accepts a field(...) accessor carrying domain ops (sort/reverse/bin).
        x: Point position, x.
        y: Point position, y.
        xMin: Range form: left/bottom edge, x.
        xMax: Range form: right/top edge, x.
        yMin: Range form: left/bottom edge, y.
        yMax: Range form: right/top edge, y.
        dims: Placement by axis name: x/y, or a name the enclosing coordinate space declares (polar theta/r, geo lon/lat). A bare value or {center} is the point, {min, max} the span.
        alignment: Cross-axis alignment for the axis without an explicit position. Default "baseline".
        w: Fixed cross-axis extent, or a field name sizing this operator's own box from data.
        h: Fixed cross-axis extent, or a field name sizing this operator's own box from data.
        debug: Dev-only flag every operator accepts and currently ignores — it is dropped before layout. Use the `log` operator to print the rows at a point in the flow.
    """
    opts: Dict[str, Any] = {}
    for _k, _v in [
        ("by", by),
        ("x", x),
        ("y", y),
        ("xMin", xMin),
        ("xMax", xMax),
        ("yMin", yMin),
        ("yMax", yMax),
        ("dims", dims),
        ("alignment", alignment),
        ("axes", axes),
        ("w", w),
        ("h", h),
        ("debug", debug),
    ]:
        if _v is not None:
            opts[_k] = _v
    return opts

def _group_opts(*, by: Any, debug: Optional[bool] = None) -> Dict[str, Any]:
    """Partition rows by `by` into a flat `Frame` (no layout beyond grouping).

    Args:
        by: Field to group rows by; also accepts a field(...) accessor carrying domain ops (sort/reverse/bin).
        debug: Dev-only flag every operator accepts and currently ignores — it is dropped before layout. Use the `log` operator to print the rows at a point in the flow.
    """
    opts: Dict[str, Any] = {}
    for _k, _v in [
        ("by", by),
        ("debug", debug),
    ]:
        if _v is not None:
            opts[_k] = _v
    return opts

def _table_opts(*, by: Any, spacing: Optional[Any] = None, numCols: Optional[float] = None, debug: Optional[bool] = None) -> Dict[str, Any]:
    """Arrange cells in a `numCols`-wide grid (or a `{x, y}` keyed grid via `by`).

    Args:
        by: Grouping fields for the column/row keys — the table operator can't run without both.
        spacing: Cell gap: a single number for both axes, or [x, y]. Default 0.
        numCols: Explicit column count (falls back to the number of distinct column keys).
        debug: Dev-only flag every operator accepts and currently ignores — it is dropped before layout. Use the `log` operator to print the rows at a point in the flow.
    """
    opts: Dict[str, Any] = {}
    for _k, _v in [
        ("by", by),
        ("spacing", spacing),
        ("numCols", numCols),
        ("debug", debug),
    ]:
        if _v is not None:
            opts[_k] = _v
    return opts

def _treemap_opts(*, x: Optional[Union[int, float, str]] = None, y: Optional[Union[int, float, str]] = None, w: Optional[Union[int, float, str]] = None, h: Optional[Union[int, float, str]] = None, by: Optional[Any] = None, paddingInner: Optional[float] = None, paddingOuter: Optional[float] = None, round: Optional[bool] = None, tile: Optional[str] = None, sort: Optional[str] = None, size: Optional[Union[int, float, str]] = None, flipY: Optional[bool] = None, leafIntrinsicRadiusField: Optional[str] = None, debug: Optional[bool] = None) -> Dict[str, Any]:
    """d3-hierarchy treemap layout over the flow's rows, fare/weight-proportional.

    Args:
        x: Left edge of the box the treemap tiles into, in the parent's space (pixels). Omitted, the parent places the treemap.
        y: Top/bottom edge (y-up: bottom) of the box the treemap tiles into, in the parent's space (pixels). Omitted, the parent places the treemap.
        w: Width of the box the treemap tiles into; a number is pixels, a data-driven value scales through the layout. Omitted, the treemap fills the slot its parent allots.
        h: Height of the box the treemap tiles into; a number is pixels, a data-driven value scales through the layout. Omitted, the treemap fills the slot its parent allots.
        by: Field to partition rows by (like spread/group); also accepts a field(...) accessor carrying domain ops (sort/reverse/bin/dropNulls). Without `by`, one leaf is emitted per row.
        paddingInner: Padding between sibling rectangles. Default 0.
        paddingOuter: Padding around the outer edge of the treemap. Default 0.
        round: Round pixel positions and sizes. Default true.
        tile: Tiling strategy. Default "squarify".
        sort: Sort leaves by weight before layout. Default "desc".
        size: Per-leaf weight driving tile area (entry-flagged per split entry); a field name aggregates (sums by default) per group.
        flipY: Mirror leaf layout top-to-bottom within the treemap box. Default false.
        leafIntrinsicRadiusField: When set, each leaf is laid out in a square of side min(leafW, leafH, 2*datum[field]).
        debug: Dev-only flag every operator accepts and currently ignores — it is dropped before layout. Use the `log` operator to print the rows at a point in the flow.
    """
    opts: Dict[str, Any] = {}
    for _k, _v in [
        ("x", x),
        ("y", y),
        ("w", w),
        ("h", h),
        ("by", by),
        ("paddingInner", paddingInner),
        ("paddingOuter", paddingOuter),
        ("round", round),
        ("tile", tile),
        ("sort", sort),
        ("size", size),
        ("flipY", flipY),
        ("leafIntrinsicRadiusField", leafIntrinsicRadiusField),
        ("debug", debug),
    ]:
        if _v is not None:
            opts[_k] = _v
    return opts

def _treemap_combinator_opts(*, x: Optional[Union[int, float, str]] = None, y: Optional[Union[int, float, str]] = None, w: Optional[Union[int, float, str]] = None, h: Optional[Union[int, float, str]] = None, by: Optional[Any] = None, paddingInner: Optional[float] = None, paddingOuter: Optional[float] = None, round: Optional[bool] = None, tile: Optional[str] = None, sort: Optional[str] = None, size: Optional[Union[int, float, str]] = None, flipY: Optional[bool] = None, leafIntrinsicRadiusField: Optional[str] = None, key: Optional[str] = None, debug: Optional[bool] = None) -> Dict[str, Any]:
    """Low-level combinator form of `treemap` (single level). Same fields as the operator form (OPERATORS.treemap) plus `key`.

    Args:
        x: Left edge of the box the treemap tiles into, in the parent's space (pixels). Omitted, the parent places the treemap.
        y: Top/bottom edge (y-up: bottom) of the box the treemap tiles into, in the parent's space (pixels). Omitted, the parent places the treemap.
        w: Width of the box the treemap tiles into; a number is pixels, a data-driven value scales through the layout. Omitted, the treemap fills the slot its parent allots.
        h: Height of the box the treemap tiles into; a number is pixels, a data-driven value scales through the layout. Omitted, the treemap fills the slot its parent allots.
        by: Field to partition rows by (like spread/group); also accepts a field(...) accessor carrying domain ops (sort/reverse/bin/dropNulls). Without `by`, one leaf is emitted per row.
        paddingInner: Padding between sibling rectangles. Default 0.
        paddingOuter: Padding around the outer edge of the treemap. Default 0.
        round: Round pixel positions and sizes. Default true.
        tile: Tiling strategy. Default "squarify".
        sort: Sort leaves by weight before layout. Default "desc".
        size: Per-leaf weight driving tile area (entry-flagged per split entry); a field name aggregates (sums by default) per group.
        flipY: Mirror leaf layout top-to-bottom within the treemap box. Default false.
        leafIntrinsicRadiusField: When set, each leaf is laid out in a square of side min(leafW, leafH, 2*datum[field]).
        key: Internal per-node key override.
        debug: Dev-only flag every operator accepts and currently ignores — it is dropped before layout. Use the `log` operator to print the rows at a point in the flow.
    """
    opts: Dict[str, Any] = {}
    for _k, _v in [
        ("x", x),
        ("y", y),
        ("w", w),
        ("h", h),
        ("by", by),
        ("paddingInner", paddingInner),
        ("paddingOuter", paddingOuter),
        ("round", round),
        ("tile", tile),
        ("sort", sort),
        ("size", size),
        ("flipY", flipY),
        ("leafIntrinsicRadiusField", leafIntrinsicRadiusField),
        ("key", key),
        ("debug", debug),
    ]:
        if _v is not None:
            opts[_k] = _v
    return opts

def _line_opts(*, fill: Optional[str] = None, stroke: Optional[str] = None, strokeWidth: Optional[float] = None, strokeDasharray: Optional[str] = None, opacity: Optional[float] = None, mixBlendMode: Optional[str] = None, curve: Optional[Any] = None, dir: Optional[str] = None, source: Optional[Any] = None, target: Optional[Any] = None, from_: Optional[str] = None, to: Optional[str] = None, along: Optional[str] = None, emX: Optional[bool] = None, emY: Optional[bool] = None, w: Optional[Union[int, float, str]] = None, h: Optional[Union[int, float, str]] = None, debug: Optional[bool] = None) -> Dict[str, Any]:
    """Center-mode connector — the path between the centers of consecutive marks (the drop-in for the removed `connect`). Bag form over a ref array, or pairwise `{from, to}` form over rows with two ref columns.

    Args:
        fill: A line's path is never filled. `fill` is the channel the shared color scale reads, so a field name colors each line by group, and it is the line color when `stroke` is omitted.
        stroke: Line color.
        strokeWidth: Line thickness in pixels. Default 1.
        strokeDasharray: Raw SVG stroke-dasharray (e.g. "12") for a dashed line.
        opacity: Opacity, 0 to 1.
        mixBlendMode: Blend mode where connectors overlap.
        curve: Screen-space path shape: a factory call (straight()/bezier()/catmullRom()/orthogonal()/arc({direction})/perfectArrows({bow})/...) or a bare name. Omitted = "auto" (catmullRom on a homogeneous continuous connection axis, else straight).
        dir: Connection axis.
        source: Anchor-mode start point: a normalized [fx, fy] on the mark's bbox, or a start/middle/end keyword.
        target: Anchor-mode end point; see `source`.
        from_: Pairwise form: column holding the source ref.
        to: Pairwise form: column holding the target ref.
        along: Names a flow tier by its `by` field: that tier becomes the path tier (threading its groups in order) and every OTHER grouping tier splits. Omitted: the path tier is inferred from the flow shape. Naming a field that matches no tier, or using `along` where the mark doesn't fuse over this chart's own flow (a refs bag, or the pairwise from/to form), is an error.
        emX: Blank-fusion anchor key: placed directly in `.mark()` position, `line(opts)` elaborates to an invisible anchor tier (a `blank()` carrying just `{w, h, emX, emY}`) plus this connector — see the `mark` construct's doc. Ignored by `line` itself.
        emY: Blank-fusion anchor key — see `emX`. Ignored by `line` itself.
        w: Blank-fusion anchor key — see `emX`. Ignored by `line` itself.
        h: Blank-fusion anchor key — see `emX`. Ignored by `line` itself.
        debug: Dev-only flag: on the shape marks (rect, circle, ellipse, petal, text, image, polygon, blank) it logs the mark's key and datum to the console as the mark is built. It changes nothing about what is drawn; the connector marks accept it and ignore it.
    """
    opts: Dict[str, Any] = {}
    for _k, _v in [
        ("fill", fill),
        ("stroke", stroke),
        ("strokeWidth", strokeWidth),
        ("strokeDasharray", strokeDasharray),
        ("opacity", opacity),
        ("mixBlendMode", mixBlendMode),
        ("curve", curve),
        ("dir", dir),
        ("source", source),
        ("target", target),
        ("from", from_),
        ("to", to),
        ("along", along),
        ("emX", emX),
        ("emY", emY),
        ("w", w),
        ("h", h),
        ("debug", debug),
    ]:
        if _v is not None:
            opts[_k] = _v
    return opts

def _ribbon_opts(*, fill: Optional[str] = None, stroke: Optional[str] = None, strokeWidth: Optional[float] = None, opacity: Optional[float] = None, mixBlendMode: Optional[str] = None, dir: Optional[str] = None, curve: Optional[Any] = None, from_: Optional[str] = None, to: Optional[str] = None, along: Optional[str] = None, emX: Optional[bool] = None, emY: Optional[bool] = None, w: Optional[Union[int, float, str]] = None, h: Optional[Union[int, float, str]] = None, debug: Optional[bool] = None) -> Dict[str, Any]:
    """Edge-mode connector — a filled band between the facing edges of consecutive marks (areas, streamgraphs, sankey ribbons).

    Args:
        fill: Fill color of the band, or a field name for a color scale. Omitted, the band takes the color of the marks it connects.
        stroke: Stroke color.
        strokeWidth: Stroke width in pixels. Default 0.
        opacity: Opacity, 0 to 1.
        mixBlendMode: Blend mode where bands overlap. Default "normal".
        dir: Connection axis.
        curve: Screen-space band-edge shape (straight() | bezier()). Omitted = "auto" (bezier).
        along: Names a flow tier by its `by` field: that tier becomes the path tier (threading its groups in order) and every OTHER grouping tier splits. Omitted: the path tier is inferred from the flow shape. Naming a field that matches no tier, or using `along` where the mark doesn't fuse over this chart's own flow (a refs bag, or the pairwise from/to form), is an error.
        emX: Blank-fusion anchor key: placed directly in `.mark()` position, `ribbon(opts)` elaborates to an invisible anchor tier (a `blank()` carrying just `{w, h, emX, emY}`) plus this connector — see the `mark` construct's doc. Ignored by `ribbon` itself.
        emY: Blank-fusion anchor key — see `emX`. Ignored by `ribbon` itself.
        w: Blank-fusion anchor key — see `emX`. Ignored by `ribbon` itself.
        h: Blank-fusion anchor key — see `emX`. Ignored by `ribbon` itself.
        debug: Dev-only flag: on the shape marks (rect, circle, ellipse, petal, text, image, polygon, blank) it logs the mark's key and datum to the console as the mark is built. It changes nothing about what is drawn; the connector marks accept it and ignore it.
    """
    opts: Dict[str, Any] = {}
    for _k, _v in [
        ("fill", fill),
        ("stroke", stroke),
        ("strokeWidth", strokeWidth),
        ("opacity", opacity),
        ("mixBlendMode", mixBlendMode),
        ("dir", dir),
        ("curve", curve),
        ("from", from_),
        ("to", to),
        ("along", along),
        ("emX", emX),
        ("emY", emY),
        ("w", w),
        ("h", h),
        ("debug", debug),
    ]:
        if _v is not None:
            opts[_k] = _v
    return opts

def _layer_opts(*, x: Optional[Union[int, float, str]] = None, cx: Optional[Union[int, float, str]] = None, x2: Optional[Union[int, float, str]] = None, w: Optional[Union[int, float, str]] = None, emX: Optional[bool] = None, y: Optional[Union[int, float, str]] = None, cy: Optional[Union[int, float, str]] = None, y2: Optional[Union[int, float, str]] = None, h: Optional[Union[int, float, str]] = None, emY: Optional[bool] = None, dims: Optional[Any] = None, key: Optional[str] = None, coord: Optional[Any] = None, axes: Optional[Any] = None, transform: Optional[Any] = None, box: Optional[bool] = None) -> Dict[str, Any]:
    """Compose children on the same canvas at (0, 0) unless placed by constraints. Also accepts explicit box dims when given a self-scaling size.

    Args:
        x: Left edge position.
        cx: Center x.
        x2: Right edge position.
        w: Width.
        emX: Embed x in the parent's x space.
        y: Top/bottom edge position (y-up: bottom).
        cy: Center y.
        y2: Other y edge position.
        h: Height.
        emY: Embed y in the parent's y space.
        dims: Box dimensions by axis name: x/y, or a name the enclosing coordinate space declares (polar theta/r, geo lon/lat). Each value is a position (like x) or an interval {min, center, max, size, embedded}.
        key: Internal per-node key override.
        coord: Coordinate transform (`polar()`, `clock()`, `wavy()`, ...) the children are drawn in. Given one, the layer becomes that coordinate boundary.
        axes: Draw the coordinate axes of this layer's `coord`. Ignored on a layer with no `coord`.
        transform: Non-affine-foldable scale applied to the composed children.
        box: True renders this as a coordinate-space transparent "box" boundary rather than a plain layer.
    """
    opts: Dict[str, Any] = {}
    for _k, _v in [
        ("x", x),
        ("cx", cx),
        ("x2", x2),
        ("w", w),
        ("emX", emX),
        ("y", y),
        ("cy", cy),
        ("y2", y2),
        ("h", h),
        ("emY", emY),
        ("dims", dims),
        ("key", key),
        ("coord", coord),
        ("axes", axes),
        ("transform", transform),
        ("box", box),
    ]:
        if _v is not None:
            opts[_k] = _v
    return opts


# --- Coord transforms ---------------------------------------------------------

def _polar_config(transform_type: str, *, inner_radius: Optional[float] = None, central_angle: Optional[float] = None, start_angle: Optional[float] = None, direction: Optional[float] = None, center: Optional[Any] = None) -> Dict[str, Any]:
    """Shared builder for the polar-family coord configs (polar()/clock()).

    Only set options are emitted, so defaults stay on the JS side. Wire keys
    are camelCase to match the JS ``PolarOptions``.

    Args:
        inner_radius: Donut hole as a fraction [0,1) of the outer radius. Default 0.
        central_angle: Total angular sweep in radians. Default 6.283185307179586.
        start_angle: Angle (radians) of θ=0. Default 1.5707963267948966.
        direction: +1 counter-clockwise, -1 clockwise (numeric ±1). Default -1.
        center: Screen-space center offset. Default [0,0].
    """
    cfg: Dict[str, Any] = {"type": transform_type}
    for _k, _v in [
        ("innerRadius", inner_radius),
        ("centralAngle", central_angle),
        ("startAngle", start_angle),
        ("direction", direction),
        ("center", center),
    ]:
        if _v is not None:
            cfg[_k] = list(_v) if _k == "center" else _v
    return cfg

