# GENERATED by packages/gofish-python/scripts/generate.ts from gofish-ir
# descriptors — do not edit; run `pnpm --filter gofish-python gen`.
"""Mechanical factory layer generated from the gofish-ir frontend descriptor
table (packages/gofish-ir/src/frontend/descriptors.ts). See
apps/docs/docs/internals/design/python-wrapper-codegen.md.

`gofish/ast.py` imports from here for the constructs whose Python body is
pure kwargs-collection + wire-key rename; dispatch logic (dual-form
operator-vs-combinator, ref-shape narrowing, DataFrame conversion, the
lambda/RPC bridge) stays hand-written there.
"""

from typing import Any, Dict, List, Optional, Union

from .ast import Mark, _channel


# --- Nested option dicts -----------------------------------------------------

# The key structure of each named option type (descriptors.ts OPTION_TYPES):
# ("object", {py_key: (wire_key, shape)}), ("ref", name), ("array", shape),
# ("tuple", (shape, ...)), ("record", value_shape),
# ("tagged", tag_key, {tag_value: shape}); None passes a value through.
_OPTION_TYPES: Dict[str, Any] = {
    "AxisOptions": ("object", {"title": ("title", None), "side": ("side", None), "label_angle": ("labelAngle", None)}),
    "AxesOptions": ("object", {"x": ("x", ("ref", "AxisOptions")), "y": ("y", ("ref", "AxisOptions"))}),
}


def _to_wire(shape: Any, value: Any, path: str) -> Any:
    """Rename the keys of a nested option value from Python to wire spelling.

    `shape` is the value's declared type, compiled from the descriptor table,
    so only declared option keys are renamed (`label_angle` to `labelAngle`,
    by the same rule as top-level kwargs). A key the type does not declare
    raises TypeError, as an unknown kwarg does. Record keys (column names,
    axis names) and values of any other type pass through unchanged. A
    tagged union picks its branch by the dict's tag key (`kind`); a missing
    or unknown tag raises TypeError.
    """
    if shape is None or value is None:
        return value
    kind = shape[0]
    if kind == "ref":
        return _to_wire(_OPTION_TYPES[shape[1]], value, path)
    if kind == "object":
        if not isinstance(value, dict):
            return value
        fields = shape[1]
        out: Dict[str, Any] = {}
        for key, item in value.items():
            if key not in fields:
                hint = next(
                    (py for py, (wire, _) in fields.items() if wire == key),
                    None,
                )
                raise TypeError(
                    f"{path} got an unexpected key {key!r}"
                    + (f" (did you mean {hint!r}?)" if hint else "")
                    + f"; expected one of {', '.join(map(repr, fields))}"
                )
            wire, sub = fields[key]
            out[wire] = _to_wire(sub, item, f"{path}[{key!r}]")
        return out
    if kind == "tagged":
        if not isinstance(value, dict):
            return value
        tag, branches = shape[1], shape[2]
        expected = ", ".join(map(repr, branches))
        if tag not in value:
            raise TypeError(f"{path} is missing the key {tag!r}; expected {tag!r} to be one of {expected}")
        branch = value[tag]
        if not isinstance(branch, str) or branch not in branches:
            raise TypeError(f"{path}[{tag!r}] got an unexpected value {branch!r}; expected one of {expected}")
        return _to_wire(branches[branch], value, path)
    if kind == "record":
        if not isinstance(value, dict):
            return value
        return {
            key: _to_wire(shape[1], item, f"{path}[{key!r}]")
            for key, item in value.items()
        }
    if kind == "array":
        if not isinstance(value, (list, tuple)):
            return value
        return [_to_wire(shape[1], item, f"{path}[{i}]") for i, item in enumerate(value)]
    if kind == "tuple":
        if not isinstance(value, (list, tuple)):
            return value
        return [
            _to_wire(sub, item, f"{path}[{i}]")
            for i, (sub, item) in enumerate(zip(shape[1], value))
        ]
    raise AssertionError(f"unknown shape kind {kind!r}")


# --- Leaf marks -------------------------------------------------------------

def rect(*, debug: Optional[bool] = None, x: Optional[Union[int, float, str]] = None, cx: Optional[Union[int, float, str]] = None, x2: Optional[Union[int, float, str]] = None, w: Optional[Union[int, float, str]] = None, em_x: Optional[bool] = None, y: Optional[Union[int, float, str]] = None, cy: Optional[Union[int, float, str]] = None, y2: Optional[Union[int, float, str]] = None, h: Optional[Union[int, float, str]] = None, em_y: Optional[bool] = None, dims: Optional[Any] = None, fill: Optional[str] = None, stroke: Optional[str] = None, stroke_width: Optional[float] = None, opacity: Optional[float] = None, filter: Optional[str] = None, key: Optional[str] = None, rx: Optional[float] = None, ry: Optional[float] = None, aspect_ratio: Optional[float] = None) -> Mark:
    """A rectangle. Box geometry via the shared dims channels.

    Args:
        debug: Dev-only flag: logs this mark's key and datum to the console as it is built. It changes nothing about what is drawn.
        x: Left edge position.
        cx: Center x.
        x2: Right edge position.
        w: Width.
        em_x: Embed x in the parent's x space.
        y: Top/bottom edge position (y-up: bottom).
        cy: Center y.
        y2: Other y edge position.
        h: Height.
        em_y: Embed y in the parent's y space.
        dims: Box dimensions by axis name: x/y, or a name the enclosing coordinate space declares (polar theta/r, geo lon/lat). Each value is a position (like x) or an interval {min, center, max, size, embedded}.
        fill: Fill color, or a field name for a color scale.
        stroke: Stroke color. Defaults to `fill`.
        stroke_width: Stroke width in pixels. Default 0.
        opacity: Opacity, 0 to 1. Default 1.
        filter: Raw SVG filter attribute.
        key: Internal per-node key override.
        rx: Corner radius, x. Default 0.
        ry: Corner radius, y. Default 0.
        aspect_ratio: w/h ratio to enforce; the constraining axis wins when both are data-driven.
    """
    _kw: Dict[str, Any] = {}
    for _k, _v in [
        ("debug", debug),
        ("x", x),
        ("cx", cx),
        ("x2", x2),
        ("w", w),
        ("emX", em_x),
        ("y", y),
        ("cy", cy),
        ("y2", y2),
        ("h", h),
        ("emY", em_y),
        ("dims", dims),
        ("fill", fill),
        ("stroke", stroke),
        ("strokeWidth", stroke_width),
        ("opacity", opacity),
        ("filter", filter),
        ("key", key),
        ("rx", rx),
        ("ry", ry),
        ("aspectRatio", aspect_ratio),
    ]:
        if _v is not None:
            _kw[_k] = _channel(_v)
    return Mark("rect", **_kw)

def circle(*, debug: Optional[bool] = None, r: Optional[Union[int, float, str]] = None, fill: Optional[str] = None, stroke: Optional[str] = None, stroke_width: Optional[float] = None, opacity: Optional[float] = None, **kwargs: Any) -> Mark:
    """A circle, drawn as an aspect-locked ellipse. Does NOT support the boxDims positioning channels directly (JS `circle()` in marks/chart.ts destructures only r/fill/stroke/strokeWidth/opacity) — position it via `spread`/`scatter`.

    Args:
        debug: Dev-only flag: logs this mark's key and datum to the console as it is built. It changes nothing about what is drawn.
        r: Radius; becomes w=h=2r on the underlying ellipse.
        fill: Fill color, or a field name for a color scale.
        stroke: Stroke color. Defaults to `fill`.
        stroke_width: Stroke width in pixels. Default 0.
        opacity: Opacity, 0 to 1, applied to fill and stroke. In JS it may also be a per-datum accessor or a `live(...)` value; only a literal number crosses the wire. Default 1.
    """
    _kw: Dict[str, Any] = {}
    for _k, _v in [
        ("debug", debug),
        ("r", r),
        ("fill", fill),
        ("stroke", stroke),
        ("strokeWidth", stroke_width),
        ("opacity", opacity),
    ]:
        if _v is not None:
            _kw[_k] = _channel(_v)
    for _k, _v in kwargs.items():
        if _v is not None:
            _kw[_k] = _channel(_v)
    return Mark("circle", **_kw)

def ellipse(*, debug: Optional[bool] = None, x: Optional[Union[int, float, str]] = None, cx: Optional[Union[int, float, str]] = None, x2: Optional[Union[int, float, str]] = None, w: Optional[Union[int, float, str]] = None, em_x: Optional[bool] = None, y: Optional[Union[int, float, str]] = None, cy: Optional[Union[int, float, str]] = None, y2: Optional[Union[int, float, str]] = None, h: Optional[Union[int, float, str]] = None, em_y: Optional[bool] = None, dims: Optional[Any] = None, fill: Optional[str] = None, stroke: Optional[str] = None, stroke_width: Optional[float] = None, opacity: Optional[float] = None, aspect_ratio: Optional[float] = None, **kwargs: Any) -> Mark:
    """An ellipse. Box geometry via the shared dims channels; paint is a strict subset of `paint` (no filter).

    Args:
        debug: Dev-only flag: logs this mark's key and datum to the console as it is built. It changes nothing about what is drawn.
        x: Left edge position.
        cx: Center x.
        x2: Right edge position.
        w: Width.
        em_x: Embed x in the parent's x space.
        y: Top/bottom edge position (y-up: bottom).
        cy: Center y.
        y2: Other y edge position.
        h: Height.
        em_y: Embed y in the parent's y space.
        dims: Box dimensions by axis name: x/y, or a name the enclosing coordinate space declares (polar theta/r, geo lon/lat). Each value is a position (like x) or an interval {min, center, max, size, embedded}.
        fill: Fill color, or a field name for a color scale.
        stroke: Stroke color. Defaults to `fill`.
        stroke_width: Stroke width in pixels. Default 0.
        opacity: Opacity, 0 to 1. Default 1.
        aspect_ratio: w/h ratio to enforce. When both dims are data-driven, the constraining axis is used.
    """
    _kw: Dict[str, Any] = {}
    for _k, _v in [
        ("debug", debug),
        ("x", x),
        ("cx", cx),
        ("x2", x2),
        ("w", w),
        ("emX", em_x),
        ("y", y),
        ("cy", cy),
        ("y2", y2),
        ("h", h),
        ("emY", em_y),
        ("dims", dims),
        ("fill", fill),
        ("stroke", stroke),
        ("strokeWidth", stroke_width),
        ("opacity", opacity),
        ("aspectRatio", aspect_ratio),
    ]:
        if _v is not None:
            _kw[_k] = _channel(_v)
    for _k, _v in kwargs.items():
        if _v is not None:
            _kw[_k] = _channel(_v)
    return Mark("ellipse", **_kw)

def petal(*, debug: Optional[bool] = None, x: Optional[Union[int, float, str]] = None, cx: Optional[Union[int, float, str]] = None, x2: Optional[Union[int, float, str]] = None, w: Optional[Union[int, float, str]] = None, em_x: Optional[bool] = None, y: Optional[Union[int, float, str]] = None, cy: Optional[Union[int, float, str]] = None, y2: Optional[Union[int, float, str]] = None, h: Optional[Union[int, float, str]] = None, em_y: Optional[bool] = None, dims: Optional[Any] = None, fill: Optional[str] = None, stroke: Optional[str] = None, stroke_width: Optional[float] = None, **kwargs: Any) -> Mark:
    """A polar-only wedge/petal shape (Petal.tsx). Box geometry via the shared dims channels.

    Args:
        debug: Dev-only flag: logs this mark's key and datum to the console as it is built. It changes nothing about what is drawn.
        x: Left edge position.
        cx: Center x.
        x2: Right edge position.
        w: Width.
        em_x: Embed x in the parent's x space.
        y: Top/bottom edge position (y-up: bottom).
        cy: Center y.
        y2: Other y edge position.
        h: Height.
        em_y: Embed y in the parent's y space.
        dims: Box dimensions by axis name: x/y, or a name the enclosing coordinate space declares (polar theta/r, geo lon/lat). Each value is a position (like x) or an interval {min, center, max, size, embedded}.
        fill: Fill color, or a field name for a color scale.
        stroke: Stroke color. Defaults to `fill`.
        stroke_width: Stroke width in pixels. Default 0.
    """
    _kw: Dict[str, Any] = {}
    for _k, _v in [
        ("debug", debug),
        ("x", x),
        ("cx", cx),
        ("x2", x2),
        ("w", w),
        ("emX", em_x),
        ("y", y),
        ("cy", cy),
        ("y2", y2),
        ("h", h),
        ("emY", em_y),
        ("dims", dims),
        ("fill", fill),
        ("stroke", stroke),
        ("strokeWidth", stroke_width),
    ]:
        if _v is not None:
            _kw[_k] = _channel(_v)
    for _k, _v in kwargs.items():
        if _v is not None:
            _kw[_k] = _channel(_v)
    return Mark("petal", **_kw)

def text(*, debug: Optional[bool] = None, x: Optional[Union[int, float, str]] = None, cx: Optional[Union[int, float, str]] = None, x2: Optional[Union[int, float, str]] = None, w: Optional[Union[int, float, str]] = None, em_x: Optional[bool] = None, y: Optional[Union[int, float, str]] = None, cy: Optional[Union[int, float, str]] = None, y2: Optional[Union[int, float, str]] = None, h: Optional[Union[int, float, str]] = None, em_y: Optional[bool] = None, dims: Optional[Any] = None, key: Optional[str] = None, text: str, fill: Optional[str] = None, stroke: Optional[str] = None, stroke_width: Optional[float] = None, filter: Optional[str] = None, font_size: Optional[float] = None, font_family: Optional[str] = None, font_style: Optional[str] = None, font_weight: Optional[Union[float, str]] = None, debug_bounding_box: Optional[bool] = None, rotate: Optional[float] = None, text_anchor: Optional[str] = None) -> Mark:
    """A text label. Box geometry via the shared dims channels positions the text anchor.

    Args:
        debug: Dev-only flag: on the shape marks (rect, circle, ellipse, petal, text, image, polygon, blank) it logs the mark's key and datum to the console as the mark is built. It changes nothing about what is drawn; the connector marks accept it and ignore it.
        x: Left edge position.
        cx: Center x.
        x2: Right edge position.
        w: Width.
        em_x: Embed x in the parent's x space.
        y: Top/bottom edge position (y-up: bottom).
        cy: Center y.
        y2: Other y edge position.
        h: Height.
        em_y: Embed y in the parent's y space.
        dims: Box dimensions by axis name: x/y, or a name the enclosing coordinate space declares (polar theta/r, geo lon/lat). Each value is a position (like x) or an interval {min, center, max, size, embedded}.
        key: Internal per-node key override.
        text: Text content (raw channel — a literal, field name, or accessor).
        fill: Fill color, or a field name for a color scale. Default "black".
        stroke: Stroke color.
        stroke_width: Stroke width in pixels. Default 0.
        filter: Raw SVG filter attribute.
        font_size: Font size in pixels. Default 12.
        font_family: Font family. Default "system-ui, sans-serif".
        font_style: Raw CSS font-style (e.g. "italic").
        font_weight: CSS font-weight (e.g. 300, 700, "bold").
        debug_bounding_box: Draw the text's bounding box, for layout debugging. Default false.
        rotate: Rotation in degrees, applied in the chart's y-up world frame about the text anchor. Default 0.
        text_anchor: Where the text anchor — the local origin `rotate` pivots about and dims channels position — sits along the string: its first character, center, or last character. Default "start".
    """
    _kw: Dict[str, Any] = {}
    for _k, _v in [
        ("debug", debug),
        ("x", x),
        ("cx", cx),
        ("x2", x2),
        ("w", w),
        ("emX", em_x),
        ("y", y),
        ("cy", cy),
        ("y2", y2),
        ("h", h),
        ("emY", em_y),
        ("dims", dims),
        ("key", key),
        ("text", text),
        ("fill", fill),
        ("stroke", stroke),
        ("strokeWidth", stroke_width),
        ("filter", filter),
        ("fontSize", font_size),
        ("fontFamily", font_family),
        ("fontStyle", font_style),
        ("fontWeight", font_weight),
        ("debugBoundingBox", debug_bounding_box),
        ("rotate", rotate),
        ("textAnchor", text_anchor),
    ]:
        if _v is not None:
            _kw[_k] = _channel(_v)
    return Mark("text", **_kw)

def image(*, debug: Optional[bool] = None, x: Optional[Union[int, float, str]] = None, cx: Optional[Union[int, float, str]] = None, x2: Optional[Union[int, float, str]] = None, w: Optional[Union[int, float, str]] = None, em_x: Optional[bool] = None, y: Optional[Union[int, float, str]] = None, cy: Optional[Union[int, float, str]] = None, y2: Optional[Union[int, float, str]] = None, h: Optional[Union[int, float, str]] = None, em_y: Optional[bool] = None, dims: Optional[Any] = None, key: Optional[str] = None, href: str, filter: Optional[str] = None, opacity: Optional[float] = None, preserve_aspect_ratio: Optional[str] = None) -> Mark:
    """An embedded raster/SVG image. Box geometry via the shared dims channels.

    Args:
        debug: Dev-only flag: logs this mark's key and datum to the console as it is built. It changes nothing about what is drawn.
        x: Left edge position.
        cx: Center x.
        x2: Right edge position.
        w: Width.
        em_x: Embed x in the parent's x space.
        y: Top/bottom edge position (y-up: bottom).
        cy: Center y.
        y2: Other y edge position.
        h: Height.
        em_y: Embed y in the parent's y space.
        dims: Box dimensions by axis name: x/y, or a name the enclosing coordinate space declares (polar theta/r, geo lon/lat). Each value is a position (like x) or an interval {min, center, max, size, embedded}.
        key: Internal per-node key override.
        href: Image URL or data URI.
        filter: Raw SVG filter attribute.
        opacity: Opacity, 0 to 1.
        preserve_aspect_ratio: Raw SVG preserveAspectRatio value. Default "xMidYMid meet".
    """
    _kw: Dict[str, Any] = {}
    for _k, _v in [
        ("debug", debug),
        ("x", x),
        ("cx", cx),
        ("x2", x2),
        ("w", w),
        ("emX", em_x),
        ("y", y),
        ("cy", cy),
        ("y2", y2),
        ("h", h),
        ("emY", em_y),
        ("dims", dims),
        ("key", key),
        ("href", href),
        ("filter", filter),
        ("opacity", opacity),
        ("preserveAspectRatio", preserve_aspect_ratio),
    ]:
        if _v is not None:
            _kw[_k] = _channel(_v)
    return Mark("image", **_kw)

def polygon(*, debug: Optional[bool] = None, points: Any, fill: Optional[str] = None, stroke: Optional[str] = None, stroke_width: Optional[float] = None, opacity: Optional[float] = None) -> Mark:
    """A closed polygon defined by local-coordinate points (y-up), given literally or read from a field. No dims channels — the bbox is computed from `points`.

    Args:
        debug: Dev-only flag: logs this mark's key and datum to the console as it is built. It changes nothing about what is drawn.
        points: Vertex list, at least 3 points — either a literal ring, or the name of a field holding one ring per row (which is how one mark draws a whole basemap).
        fill: Fill color, or a field name for a color scale. Default "black".
        stroke: Stroke color. Defaults to `fill`.
        stroke_width: Stroke width in pixels. Default 0.
        opacity: Opacity, 0 to 1, applied to both fill and stroke. Default 1.
    """
    _kw: Dict[str, Any] = {}
    for _k, _v in [
        ("debug", debug),
        ("points", points),
        ("fill", fill),
        ("stroke", stroke),
        ("strokeWidth", stroke_width),
        ("opacity", opacity),
    ]:
        if _v is not None:
            _kw[_k] = _channel(_v)
    return Mark("polygon", **_kw)

def blank(*, debug: Optional[bool] = None, em_x: Optional[bool] = None, em_y: Optional[bool] = None, w: Optional[Union[int, float, str]] = None, h: Optional[Union[int, float, str]] = None, fill: Optional[str] = None, **kwargs: Any) -> Mark:
    """An invisible sizing/positioning guide — a rect that emits no display items at all, with a restricted channel set (no x/y/cx/cy/x2/y2/theta/r — position it via a layout operator).

    Args:
        debug: Dev-only flag: logs this mark's key and datum to the console as it is built. It changes nothing about what is drawn.
        em_x: Embed x in the parent's x space.
        em_y: Embed y in the parent's y space.
        w: Width. Default 0.
        h: Height. Default 0.
        fill: Fill color. A blank never paints; `fill` only seeds the shared color scale.
    """
    _kw: Dict[str, Any] = {}
    for _k, _v in [
        ("debug", debug),
        ("emX", em_x),
        ("emY", em_y),
        ("w", w),
        ("h", h),
        ("fill", fill),
    ]:
        if _v is not None:
            _kw[_k] = _channel(_v)
    for _k, _v in kwargs.items():
        if _v is not None:
            _kw[_k] = _channel(_v)
    return Mark("blank", **_kw)


# --- Combinator-only marks ---------------------------------------------------

def over(children: List["Mark"], *, blend_mode: Optional[str] = None) -> Mark:
    """Internal-only A ∪ B union compositing (not exported from lib.ts — use `layer`). Kept only so the deserializer can dispatch the wire type.

    Args:
        blend_mode: Blend used where the two regions combine. Default "color".
    """
    kwargs: Dict[str, Any] = {}
    for _k, _v in [
        ("blendMode", blend_mode),
    ]:
        if _v is not None:
            kwargs[_k] = _v
    return Mark("over", _children=list(children), **kwargs)

def intersect(children: List["Mark"], *, blend_mode: Optional[str] = None) -> Mark:
    """Draw only where both regions overlap: A ∩ B. Binary only.

    Args:
        blend_mode: Blend used where the two regions combine. Default "color".
    """
    kwargs: Dict[str, Any] = {}
    for _k, _v in [
        ("blendMode", blend_mode),
    ]:
        if _v is not None:
            kwargs[_k] = _v
    return Mark("inside", _children=list(children), **kwargs)

def exclude(children: List["Mark"], *, blend_mode: Optional[str] = None) -> Mark:
    """Symmetric difference (odd-overlap parity): A ^ B. Binary only.

    Args:
        blend_mode: Blend used where the two regions combine. Default "color".
    """
    kwargs: Dict[str, Any] = {}
    for _k, _v in [
        ("blendMode", blend_mode),
    ]:
        if _v is not None:
            kwargs[_k] = _v
    return Mark("xor", _children=list(children), **kwargs)

def subtract(children: List["Mark"], *, blend_mode: Optional[str] = None) -> Mark:
    """Draw A with B removed: A − B. Binary only.

    Args:
        blend_mode: Blend used where the two regions combine. Default "color".
    """
    kwargs: Dict[str, Any] = {}
    for _k, _v in [
        ("blendMode", blend_mode),
    ]:
        if _v is not None:
            kwargs[_k] = _v
    return Mark("out", _children=list(children), **kwargs)

def paint(children: List["Mark"], *, blend_mode: Optional[str] = None) -> Mark:
    """A is a base surface B is painted onto, clipped to A: A ∪ (B ∩ A). Result sized to A. Binary only.

    Args:
        blend_mode: Blend used where the two regions combine. Default "color".
    """
    kwargs: Dict[str, Any] = {}
    for _k, _v in [
        ("blendMode", blend_mode),
    ]:
        if _v is not None:
            kwargs[_k] = _v
    return Mark("atop", _children=list(children), **kwargs)

def mask(children: List["Mark"]) -> Mark:
    """Use A's region as a clip and paint B inside it without drawing A itself: B ∩ A, reporting A's bounds. Binary only. No options.
    """
    return Mark("mask", _children=list(children))

def enclose(children: List["Mark"], *, padding: Optional[float] = None, rx: Optional[float] = None, ry: Optional[float] = None, fill: Optional[str] = None, stroke: Optional[str] = None, stroke_width: Optional[float] = None, stroke_dasharray: Optional[str] = None, opacity: Optional[float] = None) -> Mark:
    """Draw a rounded-rect enclosure around the union of the children's bboxes, padded by `padding`.

    Args:
        padding: Pixels of slack between the children's bbox union and the drawn enclosure. Default 2.
        rx: Corner radius, x. Default 2.
        ry: Corner radius, y. Default 2.
        fill: Fill color of the enclosure. Default "none".
        stroke: Stroke color of the enclosure. Default "#D1D9E2".
        stroke_width: Stroke width in pixels. Default 1.
        stroke_dasharray: Raw SVG stroke-dasharray (e.g. "4 2") for a dashed enclosure.
        opacity: Opacity, 0 to 1. Default 1.
    """
    kwargs: Dict[str, Any] = {}
    for _k, _v in [
        ("padding", padding),
        ("rx", rx),
        ("ry", ry),
        ("fill", fill),
        ("stroke", stroke),
        ("strokeWidth", stroke_width),
        ("strokeDasharray", stroke_dasharray),
        ("opacity", opacity),
    ]:
        if _v is not None:
            kwargs[_k] = _v
    return Mark("enclose", _children=list(children), **kwargs)

def position(children: List["Mark"], *, key: Optional[str] = None, x: Optional[Union[int, float, str]] = None, y: Optional[Union[int, float, str]] = None) -> Mark:
    """Set a single child's min-corner (x, y) in parent coordinates — an absolute-offset placement primitive, NOT center-anchored. Unlike `enclose`'s convex-hull styling, `position` draws nothing of its own; it exists for cases (e.g. the Topology story's combinator trees) that need to place one child precisely without `enclose`'s fill/stroke/hull limits.

    Args:
        key: Internal per-node key override.
        x: Min-corner x offset.
        y: Min-corner y offset.
    """
    kwargs: Dict[str, Any] = {}
    for _k, _v in [
        ("key", key),
        ("x", x),
        ("y", y),
    ]:
        if _v is not None:
            kwargs[_k] = _v
    return Mark("position", _children=list(children), **kwargs)

def arrow(children: List["Mark"], *, bow: Optional[float] = None, stretch: Optional[float] = None, stretch_min: Optional[float] = None, stretch_max: Optional[float] = None, pad_start: Optional[float] = None, pad_end: Optional[float] = None, flip: Optional[bool] = None, straights: Optional[bool] = None, stroke: Optional[str] = None, stroke_width: Optional[float] = None, start: Optional[bool] = None) -> Mark:
    """A perfect-arrows box-to-box arrow between exactly two children.

    Args:
        bow: Baseline curvature. 0 is a straight line; higher values bow the arc further from center. Default 0.2.
        stretch: How much the bow grows as the endpoints get closer, and shrinks as they get farther apart. Default 0.5.
        stretch_min: Distance in pixels below which stretch has its full effect. Default 40.
        stretch_max: Distance in pixels above which stretch has no effect. Default 420.
        pad_start: Gap in pixels between the source box and the start of the line. Default 5.
        pad_end: Gap in pixels between the end of the line and the target box, leaving room for the arrowhead. Default 20.
        flip: Flip which side the arrow bows toward. Default false.
        straights: Allow a perfectly straight line when the endpoints are axis-aligned, instead of forcing a slight bow. Default true.
        stroke: Color of the arrow's line and head, and of the start dot when shown. Default "black".
        stroke_width: Line width; also scales the arrowhead and the start dot. Default 3.
        start: Draw a dot at the start endpoint. Default false.
    """
    kwargs: Dict[str, Any] = {}
    for _k, _v in [
        ("bow", bow),
        ("stretch", stretch),
        ("stretchMin", stretch_min),
        ("stretchMax", stretch_max),
        ("padStart", pad_start),
        ("padEnd", pad_end),
        ("flip", flip),
        ("straights", straights),
        ("stroke", stroke),
        ("strokeWidth", stroke_width),
        ("start", start),
    ]:
        if _v is not None:
            kwargs[_k] = _v
    return Mark("arrow", _children=list(children), **kwargs)


# --- Dual-form cores (dispatch stays hand-written in ast.py) -----------------

def _spread_opts(*, by: Optional[Any] = None, dir: Optional[str] = None, spacing: Optional[float] = None, alignment: Optional[str] = None, shared_scale: Optional[bool] = None, anchor: Optional[str] = None, reverse: Optional[bool] = None, glue: Optional[bool] = None, axes: Optional[Any] = None, x: Optional[Union[int, float, str]] = None, y: Optional[Union[int, float, str]] = None, w: Optional[Union[int, float, str]] = None, h: Optional[Union[int, float, str]] = None, size: Optional[Union[int, float, str]] = None, debug: Optional[bool] = None) -> Dict[str, Any]:
    """Arrange children along `dir` with spacing, aligning them on the cross axis.

    Args:
        by: Field to partition rows by; also accepts a field(...) accessor carrying domain ops (sort/reverse/bin).
        dir: Axis to spread along: x, y, or an axis name the enclosing coordinate space declares (polar theta/r, geo lon/lat).
        spacing: Gap between children, px. Default 8.
        alignment: Cross-axis alignment ("start" | "middle" | "end" | "baseline"). Default "baseline".
        shared_scale: Share one scale across all children. Default false.
        anchor: Whether spacing is measured between facing edges (edge), or as a fixed pitch between the named anchor point on each child. Default "edge".
        reverse: Reverse the children's order along dir. Default false.
        glue: Stack semantics: children glued, sizes sum; spacing forced to 0. Default false.
        x: Left edge of this operator's box, in the parent's space (pixels). Omitted, the parent places it.
        y: Top/bottom edge (y-up: bottom) of this operator's box, in the parent's space (pixels). Omitted, the parent places it.
        w: Data-driven cross-axis extent (field/datum-sized children).
        h: Data-driven cross-axis extent (field/datum-sized children).
        size: Per-entry stack-axis extent (field/datum-sized children); a field(...).normalize() accessor makes it a space-filling spine.
        debug: Dev-only flag every operator accepts and currently ignores — it is dropped before layout. Use the `log` operator to print the rows at a point in the flow.
    """
    opts: Dict[str, Any] = {}
    for _k, _v in [
        ("by", by),
        ("dir", dir),
        ("spacing", spacing),
        ("alignment", alignment),
        ("sharedScale", shared_scale),
        ("anchor", anchor),
        ("reverse", reverse),
        ("glue", glue),
        ("axes", _to_wire(("ref", "AxesOptions"), axes, "axes")),
        ("x", x),
        ("y", y),
        ("w", w),
        ("h", h),
        ("size", size),
        ("debug", debug),
    ]:
        if _v is not None:
            opts[_k] = _v
    return opts

def _stack_opts(*, by: Optional[Any] = None, dir: Optional[str] = None, spacing: Optional[float] = None, glue: Optional[bool] = None, alignment: Optional[str] = None, shared_scale: Optional[bool] = None, anchor: Optional[str] = None, reverse: Optional[bool] = None, axes: Optional[Any] = None, x: Optional[Union[int, float, str]] = None, y: Optional[Union[int, float, str]] = None, w: Optional[Union[int, float, str]] = None, h: Optional[Union[int, float, str]] = None, size: Optional[Union[int, float, str]] = None, debug: Optional[bool] = None) -> Dict[str, Any]:
    """`spread({ glue: true })` under its own wire tag — children glued together (touching, no gaps).

    Args:
        by: Field to partition rows by; also accepts a field(...) accessor carrying domain ops (sort/reverse/bin).
        dir: Axis to stack along: x, y, or an axis name the enclosing coordinate space declares (polar theta/r, geo lon/lat).
        spacing: Forwarded to the underlying spread. Glue semantics force the effective gap to 0; accepted for spread-parity.
        glue: Spread-parity passthrough; stack always glues regardless.
        alignment: Cross-axis alignment ("start" | "middle" | "end" | "baseline"). Default "baseline".
        shared_scale: Share one scale across all children. Default false.
        anchor: Whether spacing is measured between facing edges (edge), or as a fixed pitch between the named anchor point on each child. Default "edge".
        reverse: Reverse the children's order along dir. Default false.
        x: Left edge of this operator's box, in the parent's space (pixels). Omitted, the parent places it.
        y: Top/bottom edge (y-up: bottom) of this operator's box, in the parent's space (pixels). Omitted, the parent places it.
        w: Data-driven cross-axis extent (field/datum-sized children).
        h: Data-driven cross-axis extent (field/datum-sized children).
        size: Per-entry stack-axis extent (field/datum-sized children); a field(...).normalize() accessor makes it a space-filling spine.
        debug: Dev-only flag every operator accepts and currently ignores — it is dropped before layout. Use the `log` operator to print the rows at a point in the flow.
    """
    opts: Dict[str, Any] = {}
    for _k, _v in [
        ("by", by),
        ("dir", dir),
        ("spacing", spacing),
        ("glue", glue),
        ("alignment", alignment),
        ("sharedScale", shared_scale),
        ("anchor", anchor),
        ("reverse", reverse),
        ("axes", _to_wire(("ref", "AxesOptions"), axes, "axes")),
        ("x", x),
        ("y", y),
        ("w", w),
        ("h", h),
        ("size", size),
        ("debug", debug),
    ]:
        if _v is not None:
            opts[_k] = _v
    return opts

def _scatter_opts(*, by: Optional[Any] = None, x: Optional[Union[int, float, str]] = None, y: Optional[Union[int, float, str]] = None, x_min: Optional[Union[int, float, str]] = None, x_max: Optional[Union[int, float, str]] = None, y_min: Optional[Union[int, float, str]] = None, y_max: Optional[Union[int, float, str]] = None, dims: Optional[Any] = None, alignment: Optional[str] = None, overlap: Optional[Any] = None, axes: Optional[Any] = None, w: Optional[Union[int, float, str]] = None, h: Optional[Union[int, float, str]] = None, debug: Optional[bool] = None) -> Dict[str, Any]:
    """Position each child at an explicit (x, y) point or [min, max] span in data space.

    Args:
        by: Field to partition rows by; also accepts a field(...) accessor carrying domain ops (sort/reverse/bin).
        x: Point position, x.
        y: Point position, y.
        x_min: Range form: left/bottom edge, x.
        x_max: Range form: right/top edge, x.
        y_min: Range form: left/bottom edge, y.
        y_max: Range form: right/top edge, y.
        dims: Placement by axis name: x/y, or a name the enclosing coordinate space declares (polar theta/r, geo lon/lat). A bare value or {center} is the point, {min, max} the span.
        alignment: Cross-axis alignment for the axis without an explicit position. Default "baseline".
        overlap: How children keep clear of each other on the axis no field places, made by a function call. separate({padding}) is a beeswarm: each dot moves to the free spot nearest the alignment line, so the counts set the width. noise({randomness, smoothing, padding, seed}) spreads the dots inside an outline that follows how many dots share each part of the data axis: each dot adds a small bell-shaped bump, and the outline is the sum of the bumps. randomness is "blue" (default), "quasi" or "uniform". smoothing is the bandwidth of each bell in data units (default one dot wide), Infinity for a flat band, or "silverman" to compute it from the data. sina() is noise with smoothing "silverman" (a violin outline), and jitter() is noise with randomness "uniform" and smoothing Infinity (classic jitter); both make kind "noise". Both kinds grow from the `alignment` line: "middle" both ways, "start"/"baseline" to the positive side, "end" to the negative side. Omit it and every child sits on the line. Strategies move only the free axis. Linear coordinate spaces only.
        w: Fixed cross-axis extent, or a field name sizing this operator's own box from data.
        h: Fixed cross-axis extent, or a field name sizing this operator's own box from data.
        debug: Dev-only flag every operator accepts and currently ignores — it is dropped before layout. Use the `log` operator to print the rows at a point in the flow.
    """
    opts: Dict[str, Any] = {}
    for _k, _v in [
        ("by", by),
        ("x", x),
        ("y", y),
        ("xMin", x_min),
        ("xMax", x_max),
        ("yMin", y_min),
        ("yMax", y_max),
        ("dims", dims),
        ("alignment", alignment),
        ("overlap", _to_wire(("tagged", "kind", {"separate": ("object", {"kind": ("kind", None), "padding": ("padding", None)}), "noise": ("object", {"kind": ("kind", None), "randomness": ("randomness", None), "smoothing": ("smoothing", None), "padding": ("padding", None), "seed": ("seed", None)})}), overlap, "overlap")),
        ("axes", _to_wire(("ref", "AxesOptions"), axes, "axes")),
        ("w", w),
        ("h", h),
        ("debug", debug),
    ]:
        if _v is not None:
            opts[_k] = _v
    return opts

def _group_opts(*, by: Any, debug: Optional[bool] = None) -> Dict[str, Any]:
    """Partition rows by `by` into a flat `Frame` (no layout beyond grouping).

    Args:
        by: Field to group rows by; also accepts a field(...) accessor carrying domain ops (sort/reverse/bin).
        debug: Dev-only flag every operator accepts and currently ignores — it is dropped before layout. Use the `log` operator to print the rows at a point in the flow.
    """
    opts: Dict[str, Any] = {}
    for _k, _v in [
        ("by", by),
        ("debug", debug),
    ]:
        if _v is not None:
            opts[_k] = _v
    return opts

def _table_opts(*, by: Any, spacing: Optional[Any] = None, num_cols: Optional[float] = None, debug: Optional[bool] = None) -> Dict[str, Any]:
    """Arrange cells in a `numCols`-wide grid (or a `{x, y}` keyed grid via `by`).

    Args:
        by: Grouping fields for the column/row keys — the table operator can't run without both.
        spacing: Cell gap: a single number for both axes, or [x, y]. Default 0.
        num_cols: Explicit column count (falls back to the number of distinct column keys).
        debug: Dev-only flag every operator accepts and currently ignores — it is dropped before layout. Use the `log` operator to print the rows at a point in the flow.
    """
    opts: Dict[str, Any] = {}
    for _k, _v in [
        ("by", _to_wire(("object", {"x": ("x", None), "y": ("y", None)}), by, "by")),
        ("spacing", spacing),
        ("numCols", num_cols),
        ("debug", debug),
    ]:
        if _v is not None:
            opts[_k] = _v
    return opts

def _treemap_opts(*, x: Optional[Union[int, float, str]] = None, y: Optional[Union[int, float, str]] = None, w: Optional[Union[int, float, str]] = None, h: Optional[Union[int, float, str]] = None, dims: Optional[Any] = None, by: Optional[Any] = None, spacing: Optional[float] = None, padding: Optional[float] = None, round: Optional[bool] = None, tile: Optional[Any] = None, sort: Optional[str] = None, size: Optional[Union[int, float, str]] = None, debug: Optional[bool] = None) -> Dict[str, Any]:
    """d3-hierarchy treemap layout over the flow's rows, fare/weight-proportional.

    Args:
        x: Left edge of the box the treemap tiles into, in the parent's space (pixels). Omitted, the parent places the treemap.
        y: Top/bottom edge (y-up: bottom) of the box the treemap tiles into, in the parent's space (pixels). Omitted, the parent places the treemap.
        w: Width of the box the treemap tiles into; a number is pixels, a data-driven value scales through the layout. Omitted, the treemap fills the slot its parent allots.
        h: Height of the box the treemap tiles into; a number is pixels, a data-driven value scales through the layout. Omitted, the treemap fills the slot its parent allots.
        dims: The box the treemap tiles into, by axis name: x/y, or a name the enclosing coordinate space declares (polar theta/r, geo lon/lat). Each value is a position (like x) or an interval {min, center, max, size, embedded}.
        by: Field to partition rows by (like spread/group); also accepts a field(...) accessor carrying domain ops (sort/reverse/bin/dropNulls). Without `by`, one leaf is emitted per row.
        spacing: Gap between sibling tiles, in pixels. Default 0.
        padding: Inset around the outer edge of the treemap, in pixels. Default 0.
        round: Round pixel positions and sizes. Default true.
        tile: The tiling strategy, made by a function call: squarify({ ratio? }), slice(), dice(), binary(), or sliceDice(). Each is one of d3-hierarchy's tiling methods. Default {"kind":"squarify"}.
        sort: Sort leaves by weight before layout. Default "desc".
        size: Per-leaf weight driving tile area (entry-flagged per split entry); a field name aggregates (sums by default) per group.
        debug: Dev-only flag every operator accepts and currently ignores — it is dropped before layout. Use the `log` operator to print the rows at a point in the flow.
    """
    opts: Dict[str, Any] = {}
    for _k, _v in [
        ("x", x),
        ("y", y),
        ("w", w),
        ("h", h),
        ("dims", dims),
        ("by", by),
        ("spacing", spacing),
        ("padding", padding),
        ("round", round),
        ("tile", _to_wire(("tagged", "kind", {"squarify": ("object", {"kind": ("kind", None), "ratio": ("ratio", None)}), "slice": ("object", {"kind": ("kind", None)}), "dice": ("object", {"kind": ("kind", None)}), "binary": ("object", {"kind": ("kind", None)}), "sliceDice": ("object", {"kind": ("kind", None)})}), tile, "tile")),
        ("sort", sort),
        ("size", size),
        ("debug", debug),
    ]:
        if _v is not None:
            opts[_k] = _v
    return opts

def _pack_opts(*, by: Optional[Any] = None, method: Optional[Any] = None, debug: Optional[bool] = None) -> Dict[str, Any]:
    """Circle packing: place the flow's groups (or rows) so their enclosing circles touch without overlapping. Children keep their pixel size; the pack does not fit itself to the available space yet (#967).

    Args:
        by: Field to partition rows by (like spread/scatter); also accepts a field(...) accessor carrying domain ops (sort/reverse/bin/dropNulls). Without `by`, one child per row.
        method: The packing strategy, made by a function call: circles() packs each child's enclosing circle with d3's front-chain algorithm. Default {"kind":"circles"}.
        debug: Dev-only flag every operator accepts and currently ignores — it is dropped before layout. Use the `log` operator to print the rows at a point in the flow.
    """
    opts: Dict[str, Any] = {}
    for _k, _v in [
        ("by", by),
        ("method", _to_wire(("object", {"kind": ("kind", None)}), method, "method")),
        ("debug", debug),
    ]:
        if _v is not None:
            opts[_k] = _v
    return opts

def _treemap_combinator_opts(*, x: Optional[Union[int, float, str]] = None, y: Optional[Union[int, float, str]] = None, w: Optional[Union[int, float, str]] = None, h: Optional[Union[int, float, str]] = None, dims: Optional[Any] = None, by: Optional[Any] = None, spacing: Optional[float] = None, padding: Optional[float] = None, round: Optional[bool] = None, tile: Optional[Any] = None, sort: Optional[str] = None, size: Optional[Union[int, float, str]] = None, key: Optional[str] = None, debug: Optional[bool] = None) -> Dict[str, Any]:
    """Low-level combinator form of `treemap` (single level). Same fields as the operator form (OPERATORS.treemap) plus `key`.

    Args:
        x: Left edge of the box the treemap tiles into, in the parent's space (pixels). Omitted, the parent places the treemap.
        y: Top/bottom edge (y-up: bottom) of the box the treemap tiles into, in the parent's space (pixels). Omitted, the parent places the treemap.
        w: Width of the box the treemap tiles into; a number is pixels, a data-driven value scales through the layout. Omitted, the treemap fills the slot its parent allots.
        h: Height of the box the treemap tiles into; a number is pixels, a data-driven value scales through the layout. Omitted, the treemap fills the slot its parent allots.
        dims: The box the treemap tiles into, by axis name: x/y, or a name the enclosing coordinate space declares (polar theta/r, geo lon/lat). Each value is a position (like x) or an interval {min, center, max, size, embedded}.
        by: Field to partition rows by (like spread/group); also accepts a field(...) accessor carrying domain ops (sort/reverse/bin/dropNulls). Without `by`, one leaf is emitted per row.
        spacing: Gap between sibling tiles, in pixels. Default 0.
        padding: Inset around the outer edge of the treemap, in pixels. Default 0.
        round: Round pixel positions and sizes. Default true.
        tile: The tiling strategy, made by a function call: squarify({ ratio? }), slice(), dice(), binary(), or sliceDice(). Each is one of d3-hierarchy's tiling methods. Default {"kind":"squarify"}.
        sort: Sort leaves by weight before layout. Default "desc".
        size: Per-leaf weight driving tile area (entry-flagged per split entry); a field name aggregates (sums by default) per group.
        key: Internal per-node key override.
        debug: Dev-only flag every operator accepts and currently ignores — it is dropped before layout. Use the `log` operator to print the rows at a point in the flow.
    """
    opts: Dict[str, Any] = {}
    for _k, _v in [
        ("x", x),
        ("y", y),
        ("w", w),
        ("h", h),
        ("dims", dims),
        ("by", by),
        ("spacing", spacing),
        ("padding", padding),
        ("round", round),
        ("tile", _to_wire(("tagged", "kind", {"squarify": ("object", {"kind": ("kind", None), "ratio": ("ratio", None)}), "slice": ("object", {"kind": ("kind", None)}), "dice": ("object", {"kind": ("kind", None)}), "binary": ("object", {"kind": ("kind", None)}), "sliceDice": ("object", {"kind": ("kind", None)})}), tile, "tile")),
        ("sort", sort),
        ("size", size),
        ("key", key),
        ("debug", debug),
    ]:
        if _v is not None:
            opts[_k] = _v
    return opts

def _spread_combinator_opts(*, x: Optional[Union[int, float, str]] = None, cx: Optional[Union[int, float, str]] = None, x2: Optional[Union[int, float, str]] = None, w: Optional[Union[int, float, str]] = None, em_x: Optional[bool] = None, y: Optional[Union[int, float, str]] = None, cy: Optional[Union[int, float, str]] = None, y2: Optional[Union[int, float, str]] = None, h: Optional[Union[int, float, str]] = None, em_y: Optional[bool] = None, dims: Optional[Any] = None, by: Optional[Any] = None, dir: Optional[str] = None, spacing: Optional[float] = None, alignment: Optional[str] = None, shared_scale: Optional[bool] = None, anchor: Optional[str] = None, reverse: Optional[bool] = None, glue: Optional[bool] = None, axes: Optional[Any] = None, size: Optional[Union[int, float, str]] = None, key: Optional[str] = None, debug: Optional[bool] = None) -> Dict[str, Any]:
    """Low-level combinator form of `spread`. Same fields as the operator form (OPERATORS.spread) plus `key` and the full box-dims group.

    Args:
        x: Left edge of this operator's box, in the parent's space (pixels). Omitted, the parent places it.
        cx: Center x.
        x2: Right edge position.
        w: Data-driven cross-axis extent (field/datum-sized children).
        em_x: Embed x in the parent's x space.
        y: Top/bottom edge (y-up: bottom) of this operator's box, in the parent's space (pixels). Omitted, the parent places it.
        cy: Center y.
        y2: Other y edge position.
        h: Data-driven cross-axis extent (field/datum-sized children).
        em_y: Embed y in the parent's y space.
        dims: Box dimensions by axis name: x/y, or a name the enclosing coordinate space declares (polar theta/r, geo lon/lat). Each value is a position (like x) or an interval {min, center, max, size, embedded}.
        by: Field to partition rows by; also accepts a field(...) accessor carrying domain ops (sort/reverse/bin).
        dir: Axis to spread along: x, y, or an axis name the enclosing coordinate space declares (polar theta/r, geo lon/lat).
        spacing: Gap between children, px. Default 8.
        alignment: Cross-axis alignment ("start" | "middle" | "end" | "baseline"). Default "baseline".
        shared_scale: Share one scale across all children. Default false.
        anchor: Whether spacing is measured between facing edges (edge), or as a fixed pitch between the named anchor point on each child. Default "edge".
        reverse: Reverse the children's order along dir. Default false.
        glue: Stack semantics: children glued, sizes sum; spacing forced to 0. Default false.
        size: Per-entry stack-axis extent (field/datum-sized children); a field(...).normalize() accessor makes it a space-filling spine.
        key: Internal per-node key override.
        debug: Dev-only flag every operator accepts and currently ignores — it is dropped before layout. Use the `log` operator to print the rows at a point in the flow.
    """
    opts: Dict[str, Any] = {}
    for _k, _v in [
        ("x", x),
        ("cx", cx),
        ("x2", x2),
        ("w", w),
        ("emX", em_x),
        ("y", y),
        ("cy", cy),
        ("y2", y2),
        ("h", h),
        ("emY", em_y),
        ("dims", dims),
        ("by", by),
        ("dir", dir),
        ("spacing", spacing),
        ("alignment", alignment),
        ("sharedScale", shared_scale),
        ("anchor", anchor),
        ("reverse", reverse),
        ("glue", glue),
        ("axes", _to_wire(("ref", "AxesOptions"), axes, "axes")),
        ("size", size),
        ("key", key),
        ("debug", debug),
    ]:
        if _v is not None:
            opts[_k] = _v
    return opts

def _stack_combinator_opts(*, x: Optional[Union[int, float, str]] = None, cx: Optional[Union[int, float, str]] = None, x2: Optional[Union[int, float, str]] = None, w: Optional[Union[int, float, str]] = None, em_x: Optional[bool] = None, y: Optional[Union[int, float, str]] = None, cy: Optional[Union[int, float, str]] = None, y2: Optional[Union[int, float, str]] = None, h: Optional[Union[int, float, str]] = None, em_y: Optional[bool] = None, dims: Optional[Any] = None, by: Optional[Any] = None, dir: Optional[str] = None, spacing: Optional[float] = None, glue: Optional[bool] = None, alignment: Optional[str] = None, shared_scale: Optional[bool] = None, anchor: Optional[str] = None, reverse: Optional[bool] = None, axes: Optional[Any] = None, size: Optional[Union[int, float, str]] = None, key: Optional[str] = None, debug: Optional[bool] = None) -> Dict[str, Any]:
    """Low-level combinator form of `stack`. Same fields as the operator form (OPERATORS.stack) plus `key` and the full box-dims group.

    Args:
        x: Left edge of this operator's box, in the parent's space (pixels). Omitted, the parent places it.
        cx: Center x.
        x2: Right edge position.
        w: Data-driven cross-axis extent (field/datum-sized children).
        em_x: Embed x in the parent's x space.
        y: Top/bottom edge (y-up: bottom) of this operator's box, in the parent's space (pixels). Omitted, the parent places it.
        cy: Center y.
        y2: Other y edge position.
        h: Data-driven cross-axis extent (field/datum-sized children).
        em_y: Embed y in the parent's y space.
        dims: Box dimensions by axis name: x/y, or a name the enclosing coordinate space declares (polar theta/r, geo lon/lat). Each value is a position (like x) or an interval {min, center, max, size, embedded}.
        by: Field to partition rows by; also accepts a field(...) accessor carrying domain ops (sort/reverse/bin).
        dir: Axis to stack along: x, y, or an axis name the enclosing coordinate space declares (polar theta/r, geo lon/lat).
        spacing: Forwarded to the underlying spread. Glue semantics force the effective gap to 0; accepted for spread-parity.
        glue: Spread-parity passthrough; stack always glues regardless.
        alignment: Cross-axis alignment ("start" | "middle" | "end" | "baseline"). Default "baseline".
        shared_scale: Share one scale across all children. Default false.
        anchor: Whether spacing is measured between facing edges (edge), or as a fixed pitch between the named anchor point on each child. Default "edge".
        reverse: Reverse the children's order along dir. Default false.
        size: Per-entry stack-axis extent (field/datum-sized children); a field(...).normalize() accessor makes it a space-filling spine.
        key: Internal per-node key override.
        debug: Dev-only flag every operator accepts and currently ignores — it is dropped before layout. Use the `log` operator to print the rows at a point in the flow.
    """
    opts: Dict[str, Any] = {}
    for _k, _v in [
        ("x", x),
        ("cx", cx),
        ("x2", x2),
        ("w", w),
        ("emX", em_x),
        ("y", y),
        ("cy", cy),
        ("y2", y2),
        ("h", h),
        ("emY", em_y),
        ("dims", dims),
        ("by", by),
        ("dir", dir),
        ("spacing", spacing),
        ("glue", glue),
        ("alignment", alignment),
        ("sharedScale", shared_scale),
        ("anchor", anchor),
        ("reverse", reverse),
        ("axes", _to_wire(("ref", "AxesOptions"), axes, "axes")),
        ("size", size),
        ("key", key),
        ("debug", debug),
    ]:
        if _v is not None:
            opts[_k] = _v
    return opts

def _label_opts(*, position: Optional[str] = None, font_size: Optional[float] = None, color: Optional[str] = None, offset: Optional[float] = None, rotate: Optional[float] = None, font_family: Optional[str] = None, font_weight: Optional[Union[float, str]] = None, font_style: Optional[str] = None) -> Dict[str, Any]:
    """Options of one .label(accessor, **options) call.

    Args:
        position: Label position, e.g. "center", "outset-top", "inset-bottom-start".
        font_size: Font size in pixels.
        color: Label color. Omitted, it is chosen to contrast with the mark.
        offset: Offset from the shape's edge in pixels.
        rotate: Rotation in degrees.
        font_family: Font family of the label's text node. Omitted, the elaborator's own font family.
        font_weight: Font weight, e.g. "bold" or a numeric weight.
        font_style: Font style, e.g. "italic".
    """
    opts: Dict[str, Any] = {}
    for _k, _v in [
        ("position", position),
        ("fontSize", font_size),
        ("color", color),
        ("offset", offset),
        ("rotate", rotate),
        ("fontFamily", font_family),
        ("fontWeight", font_weight),
        ("fontStyle", font_style),
    ]:
        if _v is not None:
            opts[_k] = _v
    return opts

def _line_opts(*, fill: Optional[str] = None, stroke: Optional[str] = None, stroke_width: Optional[float] = None, stroke_dasharray: Optional[str] = None, opacity: Optional[float] = None, mix_blend_mode: Optional[str] = None, curve: Optional[Any] = None, dir: Optional[str] = None, source: Optional[Any] = None, target: Optional[Any] = None, from_: Optional[str] = None, to: Optional[str] = None, along: Optional[str] = None, em_x: Optional[bool] = None, em_y: Optional[bool] = None, w: Optional[Union[int, float, str]] = None, h: Optional[Union[int, float, str]] = None, debug: Optional[bool] = None) -> Dict[str, Any]:
    """Center-mode connector — the path between the centers of consecutive marks (the drop-in for the removed `connect`). Bag form over a ref array, or pairwise `{from, to}` form over rows with two ref columns.

    Args:
        fill: A line's path is never filled. `fill` is the channel the shared color scale reads, so a field name colors each line by group, and it is the line color when `stroke` is omitted.
        stroke: Line color.
        stroke_width: Line thickness in pixels. Default 1.
        stroke_dasharray: Raw SVG stroke-dasharray (e.g. "12") for a dashed line.
        opacity: Opacity, 0 to 1.
        mix_blend_mode: Blend mode where connectors overlap.
        curve: Screen-space path shape: a factory call (bezier()/orthogonal()/arc({direction})/perfectArrows({bow})/...) or a bare name ("linear"/"bezier"/"step"/"monotone"/"smooth"/"catmullRom"). "step", "linear", "monotone" and "smooth" are read over the parameter of the run, from the least to the most smooth. "step" holds every value that depends on the ordering field until the next point, then jumps: a staircase when the ordering field is an axis (a line chart over years), and straight jumps between the points when it is not (a connected scatter plot). "monotone" is piecewise monotone: between two neighboring points each coordinate only rises or only falls, so the curve never goes past either point. It does not make the whole line monotone: the line still turns where the data turns, and the turn sits exactly on the data point. For a path in x and y (a connected scatter plot) this holds for x and y separately, over the ordering field. It is the same curve as d3 curveMonotoneX and Vega-Lite interpolate "monotone". "smooth" rounds a peak a little past its point, but keeps a run of equal values flat. "catmullRom" is a centripetal Catmull-Rom through the points on screen. It can overshoot between points, and it is not used when reading values over time (a mark moving along the run follows a data-space curve). Omitted = "auto" (monotone on a homogeneous continuous connection axis, else linear).
        dir: Connection axis.
        source: Anchor-mode start point: a normalized [fx, fy] on the mark's bbox, or a start/middle/end keyword.
        target: Anchor-mode end point; see `source`.
        from_: Pairwise form: column holding the source ref.
        to: Pairwise form: column holding the target ref.
        along: Names a flow tier by its `by` field: that tier becomes the path tier (threading its groups in order) and every OTHER grouping tier splits. Omitted: the path tier is inferred from the flow shape. Naming a field that matches no tier, or using `along` where the mark doesn't fuse over this chart's own flow (a refs bag, or the pairwise from/to form), is an error.
        em_x: Blank-fusion anchor key: placed directly in `.mark()` position, `line(opts)` elaborates to an invisible anchor tier (a `blank()` carrying just `{w, h, emX, emY}`) plus this connector — see the `mark` construct's doc. Ignored by `line` itself.
        em_y: Blank-fusion anchor key — see `emX`. Ignored by `line` itself.
        w: Blank-fusion anchor key — see `emX`. Ignored by `line` itself.
        h: Blank-fusion anchor key — see `emX`. Ignored by `line` itself.
        debug: Dev-only flag: on the shape marks (rect, circle, ellipse, petal, text, image, polygon, blank) it logs the mark's key and datum to the console as the mark is built. It changes nothing about what is drawn; the connector marks accept it and ignore it.
    """
    opts: Dict[str, Any] = {}
    for _k, _v in [
        ("fill", fill),
        ("stroke", stroke),
        ("strokeWidth", stroke_width),
        ("strokeDasharray", stroke_dasharray),
        ("opacity", opacity),
        ("mixBlendMode", mix_blend_mode),
        ("curve", curve),
        ("dir", dir),
        ("source", source),
        ("target", target),
        ("from", from_),
        ("to", to),
        ("along", along),
        ("emX", em_x),
        ("emY", em_y),
        ("w", w),
        ("h", h),
        ("debug", debug),
    ]:
        if _v is not None:
            opts[_k] = _v
    return opts

def _ribbon_opts(*, fill: Optional[str] = None, stroke: Optional[str] = None, stroke_width: Optional[float] = None, opacity: Optional[float] = None, mix_blend_mode: Optional[str] = None, dir: Optional[str] = None, curve: Optional[Any] = None, from_: Optional[str] = None, to: Optional[str] = None, along: Optional[str] = None, em_x: Optional[bool] = None, em_y: Optional[bool] = None, w: Optional[Union[int, float, str]] = None, h: Optional[Union[int, float, str]] = None, debug: Optional[bool] = None) -> Dict[str, Any]:
    """Edge-mode connector — a filled band between the facing edges of consecutive marks (areas, streamgraphs, sankey ribbons).

    Args:
        fill: Fill color of the band, or a field name for a color scale. Omitted, the band takes the color of the marks it connects.
        stroke: Stroke color.
        stroke_width: Stroke width in pixels. Default 0.
        opacity: Opacity, 0 to 1.
        mix_blend_mode: Blend mode where bands overlap. Default "normal".
        dir: Connection axis.
        curve: Screen-space band-edge shape ("linear" | bezier() | "step" | "monotone" | "smooth" | "catmullRom"). "step" steps both edges, as a stepped area does. "monotone" is piecewise monotone: between two neighboring points each edge only rises or only falls, so it never goes past either point, though the band still turns where the data turns (d3 curveMonotoneX, Vega-Lite interpolate "monotone"); "smooth" is a rounder reading over the same parameter, and can go a little past a point; "catmullRom" is a centripetal Catmull-Rom on screen and can overshoot. Omitted = "auto" (monotone on a homogeneous continuous connection axis, else a bezier band).
        along: Names a flow tier by its `by` field: that tier becomes the path tier (threading its groups in order) and every OTHER grouping tier splits. Omitted: the path tier is inferred from the flow shape. Naming a field that matches no tier, or using `along` where the mark doesn't fuse over this chart's own flow (a refs bag, or the pairwise from/to form), is an error.
        em_x: Blank-fusion anchor key: placed directly in `.mark()` position, `ribbon(opts)` elaborates to an invisible anchor tier (a `blank()` carrying just `{w, h, emX, emY}`) plus this connector — see the `mark` construct's doc. Ignored by `ribbon` itself.
        em_y: Blank-fusion anchor key — see `emX`. Ignored by `ribbon` itself.
        w: Blank-fusion anchor key — see `emX`. Ignored by `ribbon` itself.
        h: Blank-fusion anchor key — see `emX`. Ignored by `ribbon` itself.
        debug: Dev-only flag: on the shape marks (rect, circle, ellipse, petal, text, image, polygon, blank) it logs the mark's key and datum to the console as the mark is built. It changes nothing about what is drawn; the connector marks accept it and ignore it.
    """
    opts: Dict[str, Any] = {}
    for _k, _v in [
        ("fill", fill),
        ("stroke", stroke),
        ("strokeWidth", stroke_width),
        ("opacity", opacity),
        ("mixBlendMode", mix_blend_mode),
        ("dir", dir),
        ("curve", curve),
        ("from", from_),
        ("to", to),
        ("along", along),
        ("emX", em_x),
        ("emY", em_y),
        ("w", w),
        ("h", h),
        ("debug", debug),
    ]:
        if _v is not None:
            opts[_k] = _v
    return opts

def _layer_opts(*, x: Optional[Union[int, float, str]] = None, cx: Optional[Union[int, float, str]] = None, x2: Optional[Union[int, float, str]] = None, w: Optional[Union[int, float, str]] = None, em_x: Optional[bool] = None, y: Optional[Union[int, float, str]] = None, cy: Optional[Union[int, float, str]] = None, y2: Optional[Union[int, float, str]] = None, h: Optional[Union[int, float, str]] = None, em_y: Optional[bool] = None, dims: Optional[Any] = None, key: Optional[str] = None, coord: Optional[Any] = None, axes: Optional[Any] = None, transform: Optional[Any] = None, box: Optional[bool] = None) -> Dict[str, Any]:
    """Compose children on the same canvas at (0, 0) unless placed by constraints. Also accepts explicit box dims when given a self-scaling size.

    Args:
        x: Left edge position.
        cx: Center x.
        x2: Right edge position.
        w: Width.
        em_x: Embed x in the parent's x space.
        y: Top/bottom edge position (y-up: bottom).
        cy: Center y.
        y2: Other y edge position.
        h: Height.
        em_y: Embed y in the parent's y space.
        dims: Box dimensions by axis name: x/y, or a name the enclosing coordinate space declares (polar theta/r, geo lon/lat). Each value is a position (like x) or an interval {min, center, max, size, embedded}.
        key: Internal per-node key override.
        coord: Coordinate transform (`polar()`, `clock()`, `wavy()`, ...) the children are drawn in. Given one, the layer becomes that coordinate boundary.
        axes: Draw the coordinate axes of this layer's `coord`. Ignored on a layer with no `coord`.
        transform: Non-affine-foldable scale applied to the composed children.
        box: True renders this as a coordinate-space transparent "box" boundary rather than a plain layer.
    """
    opts: Dict[str, Any] = {}
    for _k, _v in [
        ("x", x),
        ("cx", cx),
        ("x2", x2),
        ("w", w),
        ("emX", em_x),
        ("y", y),
        ("cy", cy),
        ("y2", y2),
        ("h", h),
        ("emY", em_y),
        ("dims", dims),
        ("key", key),
        ("coord", coord),
        ("axes", _to_wire(("ref", "AxesOptions"), axes, "axes")),
        ("transform", _to_wire(("object", {"scale": ("scale", ("object", {"x": ("x", None), "y": ("y", None)}))}), transform, "transform")),
        ("box", box),
    ]:
        if _v is not None:
            opts[_k] = _v
    return opts

def _chart_opts(*, w: Optional[float] = None, h: Optional[float] = None, coord: Optional[Any] = None, color: Optional[Any] = None, axes: Optional[Any] = None, legend: Optional[bool] = None, padding: Optional[float] = None, schema: Optional[Any] = None) -> Dict[str, Any]:
    """Chart-level options for chart(data, **options).

    Args:
        w: Chart width in pixels.
        h: Chart height in pixels.
        coord: Coordinate transform for the whole chart: polar(), clock(), wavy(), ...
        color: Color scale for every mark: palette(...) or gradient(...).
        axes: Draw axes: a boolean for both axes, or per-axis options {x?, y?}.
        legend: Draw the color legend. Turned off, the marks keep their colors and only the legend is dropped. Default true.
        padding: Extra padding in pixels between the plot and the SVG edge (polar charts, overflowing labels).
        schema: Column types, keyed by column name, e.g. Schema.ordered(levels).
    """
    opts: Dict[str, Any] = {}
    for _k, _v in [
        ("w", w),
        ("h", h),
        ("coord", coord),
        ("color", color),
        ("axes", _to_wire(("ref", "AxesOptions"), axes, "axes")),
        ("legend", legend),
        ("padding", padding),
        ("schema", schema),
    ]:
        if _v is not None:
            opts[_k] = _v
    return opts


# --- Coord transforms ---------------------------------------------------------

def _polar_config(transform_type: str, *, inner_radius: Optional[float] = None, central_angle: Optional[float] = None, start_angle: Optional[float] = None, direction: Optional[float] = None, center: Optional[Any] = None) -> Dict[str, Any]:
    """Shared builder for the polar-family coord configs (polar()/clock()).

    Only set options are emitted, so defaults stay on the JS side. Wire keys
    are camelCase to match the JS ``PolarOptions``.

    Args:
        inner_radius: Donut hole as a fraction [0,1) of the outer radius. Default 0.
        central_angle: Total angular sweep in radians. Default 6.283185307179586.
        start_angle: Angle (radians) of θ=0. Default 1.5707963267948966.
        direction: +1 counter-clockwise, -1 clockwise (numeric ±1). Default -1.
        center: Screen-space center offset. Default [0,0].
    """
    cfg: Dict[str, Any] = {"type": transform_type}
    for _k, _v in [
        ("innerRadius", inner_radius),
        ("centralAngle", central_angle),
        ("startAngle", start_angle),
        ("direction", direction),
        ("center", center),
    ]:
        if _v is not None:
            cfg[_k] = list(_v) if _k == "center" else _v
    return cfg

