# GENERATED by packages/gofish-python/scripts/generate.ts from the gofish-ir
# STRATEGIES table — do not edit; run `pnpm --filter gofish-python gen`.
"""
The ``Bin`` family. The cells a key built from two fields is binned into: the value of `struct({ x, y }).bin(...)`. Each kind divides the plane of the two fields into cells that do not overlap, and puts each row in the cell its point falls in.

The package binds this module as ``Bin``, so ``Bin.hex()`` and
``from gofish.bin import hex`` reach the same function. A strategy is a
plain dict, ``{"kind": ..., **params}``, with snake_case param keys; the option it
is passed to renames them to the camelCase wire keys. Mirrors JS
``gofish-graphics/bin``.
"""

from __future__ import annotations

import math
from typing import Any, Dict, Literal, Optional

__all__ = ["hex", "voronoi"]


def hex(*, radius: float | dict) -> Dict[str, Any]:
    """A grid of hexagons with a corner at the top (pointy-top, as in d3-hexbin, ggplot2's `geom_hex` and Observable Plot), with one hexagon centered on the origin (0, 0). The grid covers the domain of the two fields in the chart's data, and every hexagon in it is a cell, empty ones included.

    Args:
        radius: The distance from a hexagon's center to its corners, in data units. A number when both fields share a unit (longitude and latitude), or `{ x, y }`, one per field, when they do not (as in ggplot2's `binwidth = c(x, y)`).
    """
    if radius is not None:
        if isinstance(radius, (int, float)) and not isinstance(radius, bool):
            if not math.isfinite(radius):
                raise ValueError(f"Bin.hex(radius=...) must be finite, got {radius!r}")
            if radius <= 0:
                raise ValueError(f"Bin.hex(radius=...) must be > 0, got {radius!r}")
        elif isinstance(radius, dict):
            for _key in radius:
                if _key not in ("x", "y"):
                    raise TypeError(f"Bin.hex(radius=...) got an unexpected key {_key!r}; expected x, y")
            if "x" not in radius:
                raise TypeError("Bin.hex(radius=...) is missing the key 'x'")
            if "x" in radius:
                radius_x = radius["x"]
                if not (isinstance(radius_x, (int, float)) and not isinstance(radius_x, bool)):
                    raise TypeError(f"Bin.hex(radius=...)['x'] must be a finite number > 0, got {type(radius_x).__name__}")
                if not math.isfinite(radius_x):
                    raise ValueError(f"Bin.hex(radius=...)['x'] must be finite, got {radius_x!r}")
                if radius_x <= 0:
                    raise ValueError(f"Bin.hex(radius=...)['x'] must be > 0, got {radius_x!r}")
            if "y" not in radius:
                raise TypeError("Bin.hex(radius=...) is missing the key 'y'")
            if "y" in radius:
                radius_y = radius["y"]
                if not (isinstance(radius_y, (int, float)) and not isinstance(radius_y, bool)):
                    raise TypeError(f"Bin.hex(radius=...)['y'] must be a finite number > 0, got {type(radius_y).__name__}")
                if not math.isfinite(radius_y):
                    raise ValueError(f"Bin.hex(radius=...)['y'] must be finite, got {radius_y!r}")
                if radius_y <= 0:
                    raise ValueError(f"Bin.hex(radius=...)['y'] must be > 0, got {radius_y!r}")
        else:
            raise TypeError(f"Bin.hex(radius=...) must be a finite number > 0 or a dict with the keys x, y, got {type(radius).__name__}")
    out: Dict[str, Any] = {"kind": "hex"}
    for _k, _v in [
        ("radius", radius),
    ]:
        if _v is not None:
            out[_k] = _v
    return out


def voronoi(*, seeds: Any) -> Dict[str, Any]:
    """One cell per seed: the points nearer to that seed than to any other (a Voronoi diagram). Each row goes to its nearest seed. The cells are clipped to the box that holds the data and the seeds.

    Args:
        seeds: The seed rows, with the same two fields as the key, such as weather stations for rain gauge readings. Pass the chart's own data to give each row its own cell.
    """
    if seeds is not None:
        from .arrow_utils import to_records
        seeds = to_records(seeds)
    if seeds is not None:
        if not isinstance(seeds, list):
            raise TypeError(f"Bin.voronoi(seeds=...) must be a table (a list of dict rows, or a dataframe), got {type(seeds).__name__}")
    out: Dict[str, Any] = {"kind": "voronoi"}
    for _k, _v in [
        ("seeds", seeds),
    ]:
        if _v is not None:
            out[_k] = _v
    return out
