# GENERATED by packages/gofish-python/scripts/generate.ts from the gofish-ir
# STRATEGIES table — do not edit; run `pnpm --filter gofish-python gen`.
"""
The ``Curve`` family. How a path runs through its points: the value of the `curve` option of `line` and `ribbon`. `linear`, `step`, `monotone` and `smooth` are read over the parameter of the run, from the least to the most smooth; `catmullRom` is a shape on screen; `bezier`, `orthogonal`, `arc` and `perfectArrows` route each pair of neighboring points.

The package binds this module as ``Curve``, so ``Curve.linear()`` and
``from gofish.curve import linear`` reach the same function. A strategy is a
plain dict, ``{"kind": ..., **params}``, with snake_case param keys; the option it
is passed to renames them to the camelCase wire keys. Mirrors JS
``gofish-graphics/curve``.
"""

from __future__ import annotations

import math
from typing import Any, Dict, Literal, Optional

__all__ = ["linear", "step", "monotone", "smooth", "catmull_rom", "bezier", "orthogonal", "arc", "perfect_arrows"]


def linear() -> Dict[str, Any]:
    """Straight segments from each point to the next."""
    return {"kind": "linear"}


def step() -> Dict[str, Any]:
    """Hold every value that depends on the ordering field until the next point, then jump: a staircase when the ordering field is an axis."""
    return {"kind": "step"}


def monotone() -> Dict[str, Any]:
    """Piecewise monotone cubic: between two neighboring points each coordinate only rises or only falls (d3 `curveMonotoneX`)."""
    return {"kind": "monotone"}


def smooth() -> Dict[str, Any]:
    """A rounder cubic over the same parameter as `monotone`; it can go a little past a point, but keeps a run of equal values flat."""
    return {"kind": "smooth"}


def catmull_rom() -> Dict[str, Any]:
    """A centripetal Catmull-Rom through the points on screen."""
    return {"kind": "catmullRom"}


def bezier() -> Dict[str, Any]:
    """Cubic bezier between each pair of points (the d3 `linkVertical`/`linkHorizontal` convention)."""
    return {"kind": "bezier"}


def orthogonal(*, bend: Optional[str] = None) -> Dict[str, Any]:
    """Right-angle elbow bending at the main-axis midpoint (GoTree orthogonal).

    Args:
        bend: Omitted, the elbow bends on the connector's `dir` axis; "auto" infers the bend axis from the endpoint geometry instead, for layouts with no single growth axis.
    """
    if bend is not None:
        if not isinstance(bend, str):
            raise TypeError(f"Curve.orthogonal(bend=...) must be \"auto\", got {type(bend).__name__}")
        if bend not in ("auto",):
            raise ValueError(f"Curve.orthogonal(bend=...) must be \"auto\", got {bend!r}")
    out: Dict[str, Any] = {"kind": "orthogonal"}
    for _k, _v in [
        ("bend", bend),
    ]:
        if _v is not None:
            out[_k] = _v
    return out


def arc(*, direction: Optional[str] = None) -> Dict[str, Any]:
    """Semicircular arc through both endpoints (GoTree arccurve).

    Args:
        direction: Which side the arc bulges toward. Default "up".
    """
    if direction is not None:
        if not isinstance(direction, str):
            raise TypeError(f"Curve.arc(direction=...) must be one of \"up\", \"down\", got {type(direction).__name__}")
        if direction not in ("up", "down"):
            raise ValueError(f"Curve.arc(direction=...) must be one of \"up\", \"down\", got {direction!r}")
    out: Dict[str, Any] = {"kind": "arc"}
    for _k, _v in [
        ("direction", direction),
    ]:
        if _v is not None:
            out[_k] = _v
    return out


def perfect_arrows(*, bow: Optional[float] = None, stretch: Optional[float] = None, stretch_min: Optional[float] = None, stretch_max: Optional[float] = None, pad_start: Optional[float] = None, pad_end: Optional[float] = None, flip: Optional[bool] = None, straights: Optional[bool] = None) -> Dict[str, Any]:
    """Box-to-box arc from the perfect-arrows library.

    Args:
        bow: Baseline curvature. 0 is a straight line. Default 0.
        stretch: How much the bow grows as the endpoints get closer, and shrinks as they get farther apart. Default 0.25.
        stretch_min: Distance in pixels below which stretch has its full effect. Default 50.
        stretch_max: Distance in pixels above which stretch has no effect. Default 420.
        pad_start: Gap in pixels between the source box and the start of the arc. Default 0.
        pad_end: Gap in pixels between the end of the arc and the target box. Default 20.
        flip: Flip which side the arc bows toward. Default false.
        straights: Allow a straight line when the endpoints are axis-aligned, instead of forcing a slight bow. Default true.
    """
    if bow is not None:
        if not (isinstance(bow, (int, float)) and not isinstance(bow, bool)):
            raise TypeError(f"Curve.perfect_arrows(bow=...) must be a number, got {type(bow).__name__}")
        if math.isnan(bow):
            raise ValueError(f"Curve.perfect_arrows(bow=...) must not be NaN, got {bow!r}")
    if stretch is not None:
        if not (isinstance(stretch, (int, float)) and not isinstance(stretch, bool)):
            raise TypeError(f"Curve.perfect_arrows(stretch=...) must be a number, got {type(stretch).__name__}")
        if math.isnan(stretch):
            raise ValueError(f"Curve.perfect_arrows(stretch=...) must not be NaN, got {stretch!r}")
    if stretch_min is not None:
        if not (isinstance(stretch_min, (int, float)) and not isinstance(stretch_min, bool)):
            raise TypeError(f"Curve.perfect_arrows(stretch_min=...) must be a number, got {type(stretch_min).__name__}")
        if math.isnan(stretch_min):
            raise ValueError(f"Curve.perfect_arrows(stretch_min=...) must not be NaN, got {stretch_min!r}")
    if stretch_max is not None:
        if not (isinstance(stretch_max, (int, float)) and not isinstance(stretch_max, bool)):
            raise TypeError(f"Curve.perfect_arrows(stretch_max=...) must be a number, got {type(stretch_max).__name__}")
        if math.isnan(stretch_max):
            raise ValueError(f"Curve.perfect_arrows(stretch_max=...) must not be NaN, got {stretch_max!r}")
    if pad_start is not None:
        if not (isinstance(pad_start, (int, float)) and not isinstance(pad_start, bool)):
            raise TypeError(f"Curve.perfect_arrows(pad_start=...) must be a number, got {type(pad_start).__name__}")
        if math.isnan(pad_start):
            raise ValueError(f"Curve.perfect_arrows(pad_start=...) must not be NaN, got {pad_start!r}")
    if pad_end is not None:
        if not (isinstance(pad_end, (int, float)) and not isinstance(pad_end, bool)):
            raise TypeError(f"Curve.perfect_arrows(pad_end=...) must be a number, got {type(pad_end).__name__}")
        if math.isnan(pad_end):
            raise ValueError(f"Curve.perfect_arrows(pad_end=...) must not be NaN, got {pad_end!r}")
    if flip is not None:
        if not isinstance(flip, bool):
            raise TypeError(f"Curve.perfect_arrows(flip=...) must be a bool, got {type(flip).__name__}")
    if straights is not None:
        if not isinstance(straights, bool):
            raise TypeError(f"Curve.perfect_arrows(straights=...) must be a bool, got {type(straights).__name__}")
    out: Dict[str, Any] = {"kind": "perfectArrows"}
    for _k, _v in [
        ("bow", bow),
        ("stretch", stretch),
        ("stretch_min", stretch_min),
        ("stretch_max", stretch_max),
        ("pad_start", pad_start),
        ("pad_end", pad_end),
        ("flip", flip),
        ("straights", straights),
    ]:
        if _v is not None:
            out[_k] = _v
    return out
