# GENERATED by packages/gofish-python/scripts/generate.ts from the gofish-ir
# STRATEGIES table — do not edit; run `pnpm --filter gofish-python gen`.
"""
The ``Overlap`` family. How `scatter` keeps its children clear of each other on the axis no field places: the value of its `overlap` option. Both kinds grow from the `alignment` line and move only that free axis.

The package binds this module as ``Overlap``, so ``Overlap.separate()`` and
``from gofish.overlap import separate`` reach the same function. A strategy is a
plain dict, ``{"kind": ..., **params}``, with snake_case param keys; the option it
is passed to renames them to the camelCase wire keys. Mirrors JS
``gofish-graphics/overlap``.
"""

import math
from typing import Any, Dict, Optional, Union

__all__ = ["separate", "noise", "sina", "jitter"]


def separate(*, padding: Optional[float] = None) -> Dict[str, Any]:
    """Keep dots apart: each dot keeps its position on the data axis and moves along the free axis to the free spot nearest the alignment line, in data order, so no two dots overlap. The result is a beeswarm (Observable Plot's `dodge`).

    Args:
        padding: Pixels kept between neighboring dots. Default 0.
    """
    if padding is not None:
        if not (isinstance(padding, (int, float)) and not isinstance(padding, bool)):
            raise TypeError(f"Overlap.separate(padding=...) must be a finite number >= 0, got {type(padding).__name__}")
        if not math.isfinite(padding):
            raise ValueError(f"Overlap.separate(padding=...) must be finite, got {padding!r}")
        if padding < 0:
            raise ValueError(f"Overlap.separate(padding=...) must be >= 0, got {padding!r}")
    out: Dict[str, Any] = {"kind": "separate"}
    for _k, _v in [
        ("padding", padding),
    ]:
        if _v is not None:
            out[_k] = _v
    return out


def noise(*, randomness: Optional[str] = None, smoothing: Optional[Union[float, str]] = None, padding: Optional[float] = None, seed: Optional[float] = None) -> Dict[str, Any]:
    """Spread the dots inside an outline that follows how many dots share each part of the data axis: each dot adds a small bell-shaped bump, and the outline is the sum of the bumps. Dots may still touch.

    Args:
        randomness: How offsets are drawn inside the outline: "blue" keeps each dot as far from its placed neighbors as it can, "quasi" spreads the dots by rank (fastest), "uniform" draws seeded uniform offsets. Default "blue".
        smoothing: The bandwidth of each dot's bell, in data units of the data axis: 0 is no smoothing beyond the dots' own size, Infinity is a flat band, and "silverman" computes it from the data. Default 0.
        padding: Pixels added to each dot's width when the outline is sized and, for "blue" randomness, when distances are compared. Default 0.
        seed: Seed for "blue" and "uniform" randomness, so a render is the same every time. Default 0.
    """
    if randomness is not None:
        if not isinstance(randomness, str):
            raise TypeError(f"Overlap.noise(randomness=...) must be one of \"blue\", \"quasi\", \"uniform\", got {type(randomness).__name__}")
        if randomness not in ("blue", "quasi", "uniform"):
            raise ValueError(f"Overlap.noise(randomness=...) must be one of \"blue\", \"quasi\", \"uniform\", got {randomness!r}")
    if smoothing is not None:
        if isinstance(smoothing, (int, float)) and not isinstance(smoothing, bool):
            if math.isnan(smoothing):
                raise ValueError(f"Overlap.noise(smoothing=...) must not be NaN, got {smoothing!r}")
            if smoothing < 0:
                raise ValueError(f"Overlap.noise(smoothing=...) must be >= 0, got {smoothing!r}")
        elif isinstance(smoothing, str):
            if smoothing not in ("silverman",):
                raise ValueError(f"Overlap.noise(smoothing=...) must be a number >= 0 or \"silverman\", got {smoothing!r}")
        else:
            raise TypeError(f"Overlap.noise(smoothing=...) must be a number >= 0 or \"silverman\", got {type(smoothing).__name__}")
    if padding is not None:
        if not (isinstance(padding, (int, float)) and not isinstance(padding, bool)):
            raise TypeError(f"Overlap.noise(padding=...) must be a finite number >= 0, got {type(padding).__name__}")
        if not math.isfinite(padding):
            raise ValueError(f"Overlap.noise(padding=...) must be finite, got {padding!r}")
        if padding < 0:
            raise ValueError(f"Overlap.noise(padding=...) must be >= 0, got {padding!r}")
    if seed is not None:
        if not (isinstance(seed, (int, float)) and not isinstance(seed, bool)):
            raise TypeError(f"Overlap.noise(seed=...) must be a finite number, got {type(seed).__name__}")
        if not math.isfinite(seed):
            raise ValueError(f"Overlap.noise(seed=...) must be finite, got {seed!r}")
    out: Dict[str, Any] = {"kind": "noise"}
    for _k, _v in [
        ("randomness", randomness),
        ("smoothing", smoothing),
        ("padding", padding),
        ("seed", seed),
    ]:
        if _v is not None:
            out[_k] = _v
    return out


def sina(*, randomness: Optional[str] = None, smoothing: Optional[Union[float, str]] = None, padding: Optional[float] = None, seed: Optional[float] = None) -> Dict[str, Any]:
    """A sina plot: noise with smoothing "silverman", a bandwidth computed per scatter from the data (ggforce's `geom_sina`). The outline is the curve a violin plot draws. Any option overrides the preset.

    Args:
        randomness: How offsets are drawn inside the outline: "blue" keeps each dot as far from its placed neighbors as it can, "quasi" spreads the dots by rank (fastest), "uniform" draws seeded uniform offsets. Default "blue".
        smoothing: The bandwidth of each dot's bell, in data units of the data axis: 0 is no smoothing beyond the dots' own size, Infinity is a flat band, and "silverman" computes it from the data. Default "silverman".
        padding: Pixels added to each dot's width when the outline is sized and, for "blue" randomness, when distances are compared. Default 0.
        seed: Seed for "blue" and "uniform" randomness, so a render is the same every time. Default 0.
    """
    if randomness is not None:
        if not isinstance(randomness, str):
            raise TypeError(f"Overlap.sina(randomness=...) must be one of \"blue\", \"quasi\", \"uniform\", got {type(randomness).__name__}")
        if randomness not in ("blue", "quasi", "uniform"):
            raise ValueError(f"Overlap.sina(randomness=...) must be one of \"blue\", \"quasi\", \"uniform\", got {randomness!r}")
    if smoothing is not None:
        if isinstance(smoothing, (int, float)) and not isinstance(smoothing, bool):
            if math.isnan(smoothing):
                raise ValueError(f"Overlap.sina(smoothing=...) must not be NaN, got {smoothing!r}")
            if smoothing < 0:
                raise ValueError(f"Overlap.sina(smoothing=...) must be >= 0, got {smoothing!r}")
        elif isinstance(smoothing, str):
            if smoothing not in ("silverman",):
                raise ValueError(f"Overlap.sina(smoothing=...) must be a number >= 0 or \"silverman\", got {smoothing!r}")
        else:
            raise TypeError(f"Overlap.sina(smoothing=...) must be a number >= 0 or \"silverman\", got {type(smoothing).__name__}")
    if padding is not None:
        if not (isinstance(padding, (int, float)) and not isinstance(padding, bool)):
            raise TypeError(f"Overlap.sina(padding=...) must be a finite number >= 0, got {type(padding).__name__}")
        if not math.isfinite(padding):
            raise ValueError(f"Overlap.sina(padding=...) must be finite, got {padding!r}")
        if padding < 0:
            raise ValueError(f"Overlap.sina(padding=...) must be >= 0, got {padding!r}")
    if seed is not None:
        if not (isinstance(seed, (int, float)) and not isinstance(seed, bool)):
            raise TypeError(f"Overlap.sina(seed=...) must be a finite number, got {type(seed).__name__}")
        if not math.isfinite(seed):
            raise ValueError(f"Overlap.sina(seed=...) must be finite, got {seed!r}")
    out: Dict[str, Any] = {"kind": "noise", "smoothing": "silverman"}
    for _k, _v in [
        ("randomness", randomness),
        ("smoothing", smoothing),
        ("padding", padding),
        ("seed", seed),
    ]:
        if _v is not None:
            out[_k] = _v
    return out


def jitter(*, randomness: Optional[str] = None, smoothing: Optional[Union[float, str]] = None, padding: Optional[float] = None, seed: Optional[float] = None) -> Dict[str, Any]:
    """Classic jitter: noise with randomness "uniform" and smoothing Infinity, so the dots get uniform random offsets in a flat band. Any option overrides the preset.

    Args:
        randomness: How offsets are drawn inside the outline: "blue" keeps each dot as far from its placed neighbors as it can, "quasi" spreads the dots by rank (fastest), "uniform" draws seeded uniform offsets. Default "uniform".
        smoothing: The bandwidth of each dot's bell, in data units of the data axis: 0 is no smoothing beyond the dots' own size, Infinity is a flat band, and "silverman" computes it from the data. Default Infinity.
        padding: Pixels added to each dot's width when the outline is sized and, for "blue" randomness, when distances are compared. Default 0.
        seed: Seed for "blue" and "uniform" randomness, so a render is the same every time. Default 0.
    """
    if randomness is not None:
        if not isinstance(randomness, str):
            raise TypeError(f"Overlap.jitter(randomness=...) must be one of \"blue\", \"quasi\", \"uniform\", got {type(randomness).__name__}")
        if randomness not in ("blue", "quasi", "uniform"):
            raise ValueError(f"Overlap.jitter(randomness=...) must be one of \"blue\", \"quasi\", \"uniform\", got {randomness!r}")
    if smoothing is not None:
        if isinstance(smoothing, (int, float)) and not isinstance(smoothing, bool):
            if math.isnan(smoothing):
                raise ValueError(f"Overlap.jitter(smoothing=...) must not be NaN, got {smoothing!r}")
            if smoothing < 0:
                raise ValueError(f"Overlap.jitter(smoothing=...) must be >= 0, got {smoothing!r}")
        elif isinstance(smoothing, str):
            if smoothing not in ("silverman",):
                raise ValueError(f"Overlap.jitter(smoothing=...) must be a number >= 0 or \"silverman\", got {smoothing!r}")
        else:
            raise TypeError(f"Overlap.jitter(smoothing=...) must be a number >= 0 or \"silverman\", got {type(smoothing).__name__}")
    if padding is not None:
        if not (isinstance(padding, (int, float)) and not isinstance(padding, bool)):
            raise TypeError(f"Overlap.jitter(padding=...) must be a finite number >= 0, got {type(padding).__name__}")
        if not math.isfinite(padding):
            raise ValueError(f"Overlap.jitter(padding=...) must be finite, got {padding!r}")
        if padding < 0:
            raise ValueError(f"Overlap.jitter(padding=...) must be >= 0, got {padding!r}")
    if seed is not None:
        if not (isinstance(seed, (int, float)) and not isinstance(seed, bool)):
            raise TypeError(f"Overlap.jitter(seed=...) must be a finite number, got {type(seed).__name__}")
        if not math.isfinite(seed):
            raise ValueError(f"Overlap.jitter(seed=...) must be finite, got {seed!r}")
    out: Dict[str, Any] = {"kind": "noise", "randomness": "uniform", "smoothing": math.inf}
    for _k, _v in [
        ("randomness", randomness),
        ("smoothing", smoothing),
        ("padding", padding),
        ("seed", seed),
    ]:
        if _v is not None:
            out[_k] = _v
    return out
