# GENERATED by packages/gofish-python/scripts/generate.ts from the gofish-ir
# STRATEGIES table — do not edit; run `pnpm --filter gofish-python gen`.
"""
The ``Tile`` family. How `treemap` tiles its box: the value of its `tile` option. Each kind is one of d3-hierarchy's tiling methods.

The package binds this module as ``Tile``, so ``Tile.squarify()`` and
``from gofish.tile import squarify`` reach the same function. A strategy is a
plain dict, ``{"kind": ..., **params}``, with snake_case param keys; the option it
is passed to renames them to the camelCase wire keys. Mirrors JS
``gofish-graphics/tile``.
"""

from typing import Any, Dict, Optional, Union

__all__ = ["squarify", "slice", "dice", "binary", "slice_dice"]


def squarify(*, ratio: Optional[float] = None) -> Dict[str, Any]:
    """Squarified tiling (d3's `treemapSquarify`): make tiles as close as possible to the aspect `ratio`. The default.

    Args:
        ratio: Target tile aspect ratio: the longer side over the shorter side, at least 1 (orientation is not chosen). Omitted, d3's default, the golden ratio. 1 aims for square tiles, which suits one circle per leaf.
    """
    out: Dict[str, Any] = {"kind": "squarify"}
    for _k, _v in [
        ("ratio", ratio),
    ]:
        if _v is not None:
            out[_k] = _v
    return out


def slice() -> Dict[str, Any]:
    """Lay the tiles out in one column, stacked along y (d3's `treemapSlice`)."""
    return {"kind": "slice"}


def dice() -> Dict[str, Any]:
    """Lay the tiles out in one row, side by side along x (d3's `treemapDice`)."""
    return {"kind": "dice"}


def binary() -> Dict[str, Any]:
    """Split the tiles into two halves of near-equal weight, recursively (d3's `treemapBinary`)."""
    return {"kind": "binary"}


def slice_dice() -> Dict[str, Any]:
    """Alternate slice and dice by depth (d3's `treemapSliceDice`)."""
    return {"kind": "sliceDice"}
