"""Equivalent of lowlevel/BumpChart.stories.tsx — Low Level Syntax/Bump Chart.

A bump chart of new-car-color popularity rankings from 2000 to 2015. Each year
is a `spread` column of dots stacked top-to-bottom by rank; every dot is named
`<Color>-<Year>`. One line per color then threads its dots across the years via
`connect`s over `ref`s to those names (the Pulley cross-tier pattern), all
wrapped in a single `layer`.
"""

from gofish import layer, spread, connect, ellipse, ref, datum
from python_stories._lowlevel_helpers import group_by, order_by

NEW_CAR_COLORS = [
    {"Color": "White (solid+pearl)", "Year": 2000, "Rank": 2},
    {"Color": "Red", "Year": 2000, "Rank": 4},
    {"Color": "Gold/yellow", "Year": 2000, "Rank": 10},
    {"Color": "Silver", "Year": 2000, "Rank": 1},
    {"Color": "Green", "Year": 2000, "Rank": 6},
    {"Color": "Brown/beige", "Year": 2000, "Rank": 8},
    {"Color": "Blue", "Year": 2000, "Rank": 7},
    {"Color": "Black (solid+effect)", "Year": 2000, "Rank": 5},
    {"Color": "Other", "Year": 2000, "Rank": 3},
    {"Color": "Gray", "Year": 2000, "Rank": 9},
    {"Color": "White (solid+pearl)", "Year": 2001, "Rank": 2},
    {"Color": "Red", "Year": 2001, "Rank": 4},
    {"Color": "Gold/yellow", "Year": 2001, "Rank": 9},
    {"Color": "Silver", "Year": 2001, "Rank": 1},
    {"Color": "Green", "Year": 2001, "Rank": 7},
    {"Color": "Brown/beige", "Year": 2001, "Rank": 8},
    {"Color": "Blue", "Year": 2001, "Rank": 5},
    {"Color": "Black (solid+effect)", "Year": 2001, "Rank": 3},
    {"Color": "Other", "Year": 2001, "Rank": 6},
    {"Color": "Gray", "Year": 2001, "Rank": 10},
    {"Color": "White (solid+pearl)", "Year": 2002, "Rank": 2},
    {"Color": "Red", "Year": 2002, "Rank": 6},
    {"Color": "Gold/yellow", "Year": 2002, "Rank": 10},
    {"Color": "Silver", "Year": 2002, "Rank": 1},
    {"Color": "Green", "Year": 2002, "Rank": 9},
    {"Color": "Brown/beige", "Year": 2002, "Rank": 8},
    {"Color": "Blue", "Year": 2002, "Rank": 4},
    {"Color": "Black (solid+effect)", "Year": 2002, "Rank": 3},
    {"Color": "Other", "Year": 2002, "Rank": 5},
    {"Color": "Gray", "Year": 2002, "Rank": 7},
    {"Color": "White (solid+pearl)", "Year": 2003, "Rank": 2},
    {"Color": "Red", "Year": 2003, "Rank": 4},
    {"Color": "Gold/yellow", "Year": 2003, "Rank": 10},
    {"Color": "Silver", "Year": 2003, "Rank": 1},
    {"Color": "Green", "Year": 2003, "Rank": 9},
    {"Color": "Brown/beige", "Year": 2003, "Rank": 7},
    {"Color": "Blue", "Year": 2003, "Rank": 6},
    {"Color": "Black (solid+effect)", "Year": 2003, "Rank": 3},
    {"Color": "Other", "Year": 2003, "Rank": 8},
    {"Color": "Gray", "Year": 2003, "Rank": 5},
    {"Color": "White (solid+pearl)", "Year": 2004, "Rank": 2},
    {"Color": "Red", "Year": 2004, "Rank": 6},
    {"Color": "Gold/yellow", "Year": 2004, "Rank": 10},
    {"Color": "Silver", "Year": 2004, "Rank": 1},
    {"Color": "Green", "Year": 2004, "Rank": 8},
    {"Color": "Brown/beige", "Year": 2004, "Rank": 5},
    {"Color": "Blue", "Year": 2004, "Rank": 4},
    {"Color": "Black (solid+effect)", "Year": 2004, "Rank": 3},
    {"Color": "Other", "Year": 2004, "Rank": 9},
    {"Color": "Gray", "Year": 2004, "Rank": 7},
    {"Color": "White (solid+pearl)", "Year": 2005, "Rank": 2},
    {"Color": "Red", "Year": 2005, "Rank": 6},
    {"Color": "Gold/yellow", "Year": 2005, "Rank": 9},
    {"Color": "Silver", "Year": 2005, "Rank": 1},
    {"Color": "Green", "Year": 2005, "Rank": 8},
    {"Color": "Brown/beige", "Year": 2005, "Rank": 7},
    {"Color": "Blue", "Year": 2005, "Rank": 4},
    {"Color": "Black (solid+effect)", "Year": 2005, "Rank": 5},
    {"Color": "Other", "Year": 2005, "Rank": 10},
    {"Color": "Gray", "Year": 2005, "Rank": 3},
    {"Color": "White (solid+pearl)", "Year": 2006, "Rank": 2},
    {"Color": "Red", "Year": 2006, "Rank": 6},
    {"Color": "Gold/yellow", "Year": 2006, "Rank": 9},
    {"Color": "Silver", "Year": 2006, "Rank": 1},
    {"Color": "Green", "Year": 2006, "Rank": 8},
    {"Color": "Brown/beige", "Year": 2006, "Rank": 7},
    {"Color": "Blue", "Year": 2006, "Rank": 5},
    {"Color": "Black (solid+effect)", "Year": 2006, "Rank": 3},
    {"Color": "Other", "Year": 2006, "Rank": 10},
    {"Color": "Gray", "Year": 2006, "Rank": 4},
    {"Color": "White (solid+pearl)", "Year": 2007, "Rank": 1},
    {"Color": "Red", "Year": 2007, "Rank": 4},
    {"Color": "Gold/yellow", "Year": 2007, "Rank": 8},
    {"Color": "Silver", "Year": 2007, "Rank": 2},
    {"Color": "Green", "Year": 2007, "Rank": 9},
    {"Color": "Brown/beige", "Year": 2007, "Rank": 7},
    {"Color": "Blue", "Year": 2007, "Rank": 5},
    {"Color": "Black (solid+effect)", "Year": 2007, "Rank": 3},
    {"Color": "Other", "Year": 2007, "Rank": 10},
    {"Color": "Gray", "Year": 2007, "Rank": 6},
    {"Color": "White (solid+pearl)", "Year": 2008, "Rank": 1},
    {"Color": "Red", "Year": 2008, "Rank": 6},
    {"Color": "Gold/yellow", "Year": 2008, "Rank": 9},
    {"Color": "Silver", "Year": 2008, "Rank": 3},
    {"Color": "Green", "Year": 2008, "Rank": 8},
    {"Color": "Brown/beige", "Year": 2008, "Rank": 7},
    {"Color": "Blue", "Year": 2008, "Rank": 4},
    {"Color": "Black (solid+effect)", "Year": 2008, "Rank": 2},
    {"Color": "Other", "Year": 2008, "Rank": 10},
    {"Color": "Gray", "Year": 2008, "Rank": 5},
    {"Color": "White (solid+pearl)", "Year": 2009, "Rank": 1},
    {"Color": "Red", "Year": 2009, "Rank": 6},
    {"Color": "Gold/yellow", "Year": 2009, "Rank": 9},
    {"Color": "Silver", "Year": 2009, "Rank": 3},
    {"Color": "Green", "Year": 2009, "Rank": 8},
    {"Color": "Brown/beige", "Year": 2009, "Rank": 7},
    {"Color": "Blue", "Year": 2009, "Rank": 5},
    {"Color": "Black (solid+effect)", "Year": 2009, "Rank": 2},
    {"Color": "Other", "Year": 2009, "Rank": 10},
    {"Color": "Gray", "Year": 2009, "Rank": 4},
    {"Color": "White (solid+pearl)", "Year": 2010, "Rank": 1},
    {"Color": "Red", "Year": 2010, "Rank": 5},
    {"Color": "Gold/yellow", "Year": 2010, "Rank": 9},
    {"Color": "Silver", "Year": 2010, "Rank": 3},
    {"Color": "Green", "Year": 2010, "Rank": 8},
    {"Color": "Brown/beige", "Year": 2010, "Rank": 7},
    {"Color": "Blue", "Year": 2010, "Rank": 6},
    {"Color": "Black (solid+effect)", "Year": 2010, "Rank": 2},
    {"Color": "Other", "Year": 2010, "Rank": 10},
    {"Color": "Gray", "Year": 2010, "Rank": 4},
    {"Color": "White (solid+pearl)", "Year": 2011, "Rank": 1},
    {"Color": "Red", "Year": 2011, "Rank": 5},
    {"Color": "Gold/yellow", "Year": 2011, "Rank": 8},
    {"Color": "Silver", "Year": 2011, "Rank": 3},
    {"Color": "Green", "Year": 2011, "Rank": 9},
    {"Color": "Brown/beige", "Year": 2011, "Rank": 7},
    {"Color": "Blue", "Year": 2011, "Rank": 6},
    {"Color": "Black (solid+effect)", "Year": 2011, "Rank": 2},
    {"Color": "Other", "Year": 2011, "Rank": 10},
    {"Color": "Gray", "Year": 2011, "Rank": 4},
    {"Color": "White (solid+pearl)", "Year": 2012, "Rank": 1},
    {"Color": "Red", "Year": 2012, "Rank": 5},
    {"Color": "Gold/yellow", "Year": 2012, "Rank": 8},
    {"Color": "Silver", "Year": 2012, "Rank": 3},
    {"Color": "Green", "Year": 2012, "Rank": 9},
    {"Color": "Brown/beige", "Year": 2012, "Rank": 7},
    {"Color": "Blue", "Year": 2012, "Rank": 6},
    {"Color": "Black (solid+effect)", "Year": 2012, "Rank": 2},
    {"Color": "Other", "Year": 2012, "Rank": 10},
    {"Color": "Gray", "Year": 2012, "Rank": 4},
    {"Color": "White (solid+pearl)", "Year": 2013, "Rank": 1},
    {"Color": "Red", "Year": 2013, "Rank": 5},
    {"Color": "Gold/yellow", "Year": 2013, "Rank": 8},
    {"Color": "Silver", "Year": 2013, "Rank": 3},
    {"Color": "Green", "Year": 2013, "Rank": 9},
    {"Color": "Brown/beige", "Year": 2013, "Rank": 7},
    {"Color": "Blue", "Year": 2013, "Rank": 6},
    {"Color": "Black (solid+effect)", "Year": 2013, "Rank": 2},
    {"Color": "Other", "Year": 2013, "Rank": 10},
    {"Color": "Gray", "Year": 2013, "Rank": 4},
    {"Color": "White (solid+pearl)", "Year": 2014, "Rank": 1},
    {"Color": "Red", "Year": 2014, "Rank": 5},
    {"Color": "Gold/yellow", "Year": 2014, "Rank": 8},
    {"Color": "Silver", "Year": 2014, "Rank": 4},
    {"Color": "Green", "Year": 2014, "Rank": 9},
    {"Color": "Brown/beige", "Year": 2014, "Rank": 7},
    {"Color": "Blue", "Year": 2014, "Rank": 6},
    {"Color": "Black (solid+effect)", "Year": 2014, "Rank": 2},
    {"Color": "Other", "Year": 2014, "Rank": 10},
    {"Color": "Gray", "Year": 2014, "Rank": 3},
    {"Color": "White (solid+pearl)", "Year": 2015, "Rank": 1},
    {"Color": "Red", "Year": 2015, "Rank": 5},
    {"Color": "Gold/yellow", "Year": 2015, "Rank": 8},
    {"Color": "Silver", "Year": 2015, "Rank": 4},
    {"Color": "Green", "Year": 2015, "Rank": 9},
    {"Color": "Brown/beige", "Year": 2015, "Rank": 7},
    {"Color": "Blue", "Year": 2015, "Rank": 6},
    {"Color": "Black (solid+effect)", "Year": 2015, "Rank": 2},
    {"Color": "Other", "Year": 2015, "Rank": 10},
    {"Color": "Gray", "Year": 2015, "Rank": 3},
]


def _dot_name(d):
    return f"{d['Color']}-{d['Year']}"


def story_default():
    by_year = group_by(NEW_CAR_COLORS, "Year")

    year_columns = [
        spread(
            [
                ellipse(w=8, h=8, fill=datum(d["Color"])).name(_dot_name(d))
                for d in order_by(rows, "Rank")
            ],
            dir="y",
            x=(year - 2000) * 30,
            spacing=16,
            alignment="start",
        )
        for year, rows in by_year.items()
    ]

    color_lines = [
        connect(
            [ref(_dot_name(d)) for d in color_rows],
            direction="y",
            strokeWidth=2,
            mode="center",
        )
        for color_rows in group_by(NEW_CAR_COLORS, "Color").values()
    ]

    return (
        layer([*year_columns, *color_lines]),
        {},
    )
