export * from "./schema.js";
export {
  validate,
  AXIS_INTERVAL_KEYS,
  isAxisInterval,
  type ValidationResult,
  type ValidationError,
} from "./validate.js";
export {
  exampleBarChart,
  exampleLayer,
  exampleScatter,
  exampleTreemap,
  exampleCustomMark,
  allExamples,
} from "./examples.js";
export { FRONTEND_IR_JSON_SCHEMA } from "./jsonSchema.js";
export {
  encodeIR,
  decodeNonFinite,
  isPlainObject,
  type NonFiniteNumberIR,
} from "./nonFinite.js";
export {
  t,
  ch,
  group,
  resolveFields,
  pyKwarg,
  OPERATORS,
  LEAF_MARKS,
  COMBINATOR_MARKS,
  COORDS,
  OPTION_TYPES,
  CHART_OPTIONS,
  OPTION_GROUPS,
  MARK_BASE_FIELDS,
  OPERATOR_BASE_FIELDS,
  PY_LEAF_BASE_KWARGS,
  PY_OPERATOR_BASE_KWARGS,
  COMBINATOR_OPTIONS_BASE_FIELDS,
  DESCRIPTOR_TABLES,
  acceptedFields,
  carriesChannel,
  LABEL_OPTIONS,
  boxDims,
  paint,
  SHARED_FIELD_GROUPS,
  ALL_OPERATOR_DESCRIPTORS,
  ALL_LEAF_MARK_DESCRIPTORS,
  ALL_COMBINATOR_MARK_DESCRIPTORS,
  ALL_COORD_DESCRIPTORS,
  type ChannelInner,
  type FieldType,
  type FieldSpec,
  type FieldGroup,
  type ConstructKind,
  type NodeKind,
  type ConstructDescriptor,
} from "./descriptors.js";
