/**
 * One-off generator for `src/data/birds.ts`.
 *
 * Downloads `bird_data.csv` (the running example of *Animated Vega-Lite*) and
 * writes it as a typed module. Run with:
 *
 *   pnpm --filter gofish-graphics exec tsx scripts/build-birds.ts
 *
 * Coordinates are rounded to three decimals (about 100 m) and the species name
 * is interned, which keeps the module around a third of the raw CSV's size.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const SOURCE =
  "https://gist.githubusercontent.com/jonathanzong/5f4fa36e8c2cd04639bc550540264dc6/raw/6cb2070b6ffdd2d4bc1a91fdd635737048414881/bird_data.csv";

const here = path.dirname(fileURLToPath(import.meta.url));
const outPath = path.join(here, "..", "src", "data", "birds.ts");

const csv = (await (await fetch(SOURCE)).text()).trim().split("\n");
const header = csv[0].trim();
if (header !== "day,lon,lat,species") {
  throw new Error(`unexpected header: ${header}`);
}

const speciesNames: string[] = [];
const speciesIndex = new Map<string, number>();
const packed: [number, number, number, number][] = [];

for (let i = 1; i < csv.length; i++) {
  const [day, lon, lat, species] = csv[i].trim().split(",");
  if (!speciesIndex.has(species)) {
    speciesIndex.set(species, speciesNames.length);
    speciesNames.push(species);
  }
  packed.push([
    Number(day),
    Math.round(Number(lon) * 1000) / 1000,
    Math.round(Number(lat) * 1000) / 1000,
    speciesIndex.get(species)!,
  ]);
}

const out = `/**
 * Bird migration paths — the running example of *Animated Vega-Lite* (Zong,
 * Pollock, Wootton, Satyanarayan, IEEE VIS 2022).
 *
 * 72 species x 365 days = ${packed.length.toLocaleString("en-US")} daily positions, no gaps. Source:
 * https://gist.github.com/jonathanzong/5f4fa36e8c2cd04639bc550540264dc6
 * (\`bird_data.csv\`, columns day,lon,lat,species). Longitude and latitude are
 * rounded to three decimals to keep the module small; \`day\` runs 1..365 and is
 * a number here, so specs need no string-to-number step.
 *
 * Generated by \`scripts/build-birds.ts\` — do not edit by hand. Rows are stored
 * column-wise with the species name interned, and decoded into records at
 * import time; the record form is what specs read.
 */
export type Bird = {
  day: number;
  lon: number;
  lat: number;
  species: string;
};

const speciesNames: string[] = ${JSON.stringify(speciesNames)};

// The packed rows are decoded inside an IIFE so the source array is unreachable
// once the module has loaded: only the decoded records are retained.
export const birds: Bird[] = (() => {
  /** [day, lon, lat, speciesIndex] */
  const packed: [number, number, number, number][] = ${JSON.stringify(packed)};
  return packed.map(([day, lon, lat, species]) => ({
    day,
    lon,
    lat,
    species: speciesNames[species],
  }));
})();

export { speciesNames as birdSpecies };
`;

fs.writeFileSync(outPath, out);
console.log(
  `wrote ${outPath}: ${speciesNames.length} species, ${packed.length} rows, ${out.length} bytes`
);
