/**
 * One-off generator for `src/data/world110m.ts`.
 *
 * Decodes vega-datasets' `world-110m.json` (TopoJSON, object `countries`) into
 * one row per polygon ring. Run with:
 *
 *   pnpm --filter gofish-graphics exec tsx scripts/build-world110m.ts
 *
 * `topojson-client` is a dev dependency used only here — the decoded rings are
 * checked in, so the library itself never depends on it.
 *
 * Declared shortcut: a MultiPolygon contributes several rows, and interior
 * rings (holes) are emitted as ordinary rings rather than as holes of their
 * outer ring. A lake inside a country therefore paints over the country instead
 * of cutting a hole in it. The right fix is a polygon mark that takes holes,
 * which nothing else needs today.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { feature } from "topojson-client";

const here = path.dirname(fileURLToPath(import.meta.url));
const outPath = path.join(here, "..", "src", "data", "world110m.ts");

// vega-datasets' `exports` map doesn't expose the raw data files (or its own
// package.json), so walk to `data/` through node_modules by hand.
const dataPath = path.join(
  here,
  "..",
  "node_modules",
  "vega-datasets",
  "data",
  "world-110m.json"
);
const topology = JSON.parse(fs.readFileSync(dataPath, "utf8"));

const countries = feature(topology, topology.objects.countries) as {
  features: {
    id?: string | number;
    geometry: {
      type: string;
      coordinates: number[][][] | number[][][][];
    } | null;
  }[];
};

const round = (n: number) => Math.round(n * 100) / 100;

const rows: { id: string; ring: [number, number][] }[] = [];

for (const f of countries.features) {
  if (!f.geometry) continue;
  const polygons =
    f.geometry.type === "Polygon"
      ? [f.geometry.coordinates as number[][][]]
      : (f.geometry.coordinates as number[][][][]);
  for (const polygon of polygons) {
    for (const ring of polygon) {
      const rounded = ring.map(
        ([lon, lat]) => [round(lon), round(lat)] as [number, number]
      );
      // A closed ring needs at least three distinct vertices; the source
      // repeats the first point as the last, so four is the floor.
      if (rounded.length < 4) continue;
      rows.push({ id: String(f.id ?? ""), ring: rounded });
    }
  }
}

const out = `/**
 * World basemap — one row per polygon ring of vega-datasets' \`world-110m.json\`
 * (TopoJSON object \`countries\`, 1:110,000,000 Natural Earth boundaries).
 *
 * Generated by \`scripts/build-world110m.ts\` — do not edit by hand. Coordinates
 * are [longitude, latitude] in degrees, rounded to two decimals.
 *
 * Declared shortcut: interior rings (holes) are emitted as ordinary rings, so a
 * lake inside a country paints over the country instead of cutting it out. The
 * right fix is a polygon mark that takes holes, which nothing else needs today.
 */
export type CountryRing = {
  /** The country's numeric ISO 3166-1 id, as a string. */
  id: string;
  /** One closed ring, [lon, lat] in degrees. */
  ring: [number, number][];
};

export const world110m: CountryRing[] = ${JSON.stringify(rows)};
`;

fs.writeFileSync(outPath, out);
console.log(`wrote ${outPath}: ${rows.length} rings, ${out.length} bytes`);
