/**
 * Generates `src/ast/markChannels.generated.ts`: each leaf mark's channel map
 * (the options its `createMark` call infers from data), from the descriptor
 * table in gofish-ir (`packages/gofish-ir/src/frontend/descriptors.ts`).
 *
 * A field is a channel when its type can hold one (`carriesChannel`): a bare
 * channel infers by its descriptor kind (`ch.size`, `ch.pos`, `ch.color`,
 * `ch.raw`), and a record of channels (the `dims` bag) is a `dims` channel.
 * The Python generator wraps a callable as an accessor at exactly the same
 * fields, so a Python lambda works exactly where JS infers a channel.
 *
 * The map is generated as a literal, not built at run time, so `createMark`'s
 * prop types (`DeriveMarkProps`) still see each key's kind. Run via
 * `pnpm --filter gofish-graphics gen` (builds gofish-ir first); CI checks that
 * the file is fresh.
 */

import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  LEAF_MARKS,
  acceptedFields,
  carriesChannel,
  type FieldType,
} from "gofish-ir/frontend";

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT_FILE = join(HERE, "..", "src", "ast", "markChannels.generated.ts");

/** The leaf marks built with `createMark`. `line` and `ribbon` are relational
 *  marks with their own factory (`createRelationalMark`). */
const CREATE_MARK_TYPES = [
  "rect",
  "circle",
  "ellipse",
  "petal",
  "text",
  "image",
  "polygon",
  "blank",
];

function channelKind(type: FieldType, where: string): string {
  if (type.kind === "channel") return type.infer;
  if (type.kind === "record" && carriesChannel(type.valueType)) return "dims";
  throw new Error(
    `${where}: a field that holds a channel must be a channel or a record of ` +
      `channels (a dims bag) for createMark to infer it.`
  );
}

const lines: string[] = [
  "// GENERATED by scripts/generate-mark-channels.ts from gofish-ir's",
  "// descriptor table. Do not edit; run `pnpm --filter gofish-graphics gen`.",
  "",
  "/** Each leaf mark's channel map, from its descriptor (`LEAF_MARKS`). */",
  "export const MARK_CHANNELS = {",
];
for (const type of CREATE_MARK_TYPES) {
  if (!(type in LEAF_MARKS))
    throw new Error(`no leaf-mark descriptor: ${type}`);
  const fields = acceptedFields("leaf-mark", type)!;
  const entries = Object.entries(fields)
    .filter(([, spec]) => carriesChannel(spec.type))
    .map(
      ([key, spec]) =>
        `    ${key}: ${JSON.stringify(channelKind(spec.type, `${type}.${key}`))},`
    );
  lines.push(`  ${type}: {`, ...entries, "  },");
}
lines.push("} as const;", "");
writeFileSync(OUT_FILE, lines.join("\n"));
console.log(`wrote ${OUT_FILE}`);
