/**
 * The GoFish context: how GoFish is presented to the model in the gofish
 * arm (`--context`). The other arms get no documentation.
 *
 *   - `pack:<path>`: a docs pack appended to the system prompt (the v1 and v2
 *     packs are context/gofish.md and context/gofish-v2.md).
 *   - `cheatsheet`: context/cheatsheet.md in the system prompt, a compact
 *     reference generated by make-cheatsheet.ts.
 *   - `retrieval`: the cheatsheet in the system prompt, plus the three
 *     gallery examples most similar to the task's instruction (BM25 over
 *     context/gallery-index.json), put in the user message so the system
 *     prompt stays cacheable.
 *   - `skill`: claude-code only. The folder context/skill/ (SKILL.md and one
 *     file per gallery example) is copied into the call's working directory,
 *     and the model reads it with the Read, Glob and Grep tools.
 */

import { createHash } from "crypto";
import { existsSync, readdirSync, readFileSync, statSync } from "fs";
import { basename, join, relative, resolve } from "path";
import { BENCH_DIR } from "./tasks";

export const CONTEXT_DIR = join(BENCH_DIR, "context");
export const CHEATSHEET_PATH = join(CONTEXT_DIR, "cheatsheet.md");
export const GALLERY_INDEX_PATH = join(CONTEXT_DIR, "gallery-index.json");
export const SKILL_DIR = join(CONTEXT_DIR, "skill");
export const DEFAULT_CONTEXT = "pack:context/gofish.md";

/** One gallery example in the index. */
export interface GalleryEntry {
  id: string;
  title: string;
  description: string;
  /** The standalone example as JavaScript. */
  code: string;
}

/** What a run records about its context, on every job. */
export interface ContextInfo {
  /** "pack:gofish-v2.md", "cheatsheet", "retrieval" or "skill". */
  name: string;
  /** The first 12 hex characters of the sha256 of everything the context
   *  can send (for a skill, every file in the folder). */
  sha256: string;
}

export interface GofishContext extends ContextInfo {
  /** Appended to the gofish arm's system prompt (after the arm prompt). */
  systemText: string;
  /** Retrieval: the examples for an instruction. */
  retrieve?: (instruction: string) => GalleryEntry[];
  /** Skill: the folder copied into each call's working directory. */
  skillDir?: string;
}

/** A job's context, also for results from before `context` was recorded,
 *  which kept the docs pack in `docsPack` (a pack is the only context they
 *  could have had). Undefined when neither was recorded. */
export function contextOf(r: {
  context?: ContextInfo;
  docsPack?: { file: string; sha256: string };
}): ContextInfo | undefined {
  if (r.context) return r.context;
  if (r.docsPack)
    return { name: `pack:${r.docsPack.file}`, sha256: r.docsPack.sha256 };
  return undefined;
}

/** The first 12 hex characters of the sha256 of the parts joined by NUL (so
 *  a pack's hash is its file's, as recorded before contexts existed). */
const hash = (parts: string[]) =>
  createHash("sha256").update(parts.join("\0")).digest("hex").slice(0, 12);

/** Every file under `dir`, as [relative path, contents], in sorted order. */
function folderFiles(dir: string): [string, string][] {
  const out: [string, string][] = [];
  const walk = (d: string) => {
    for (const f of readdirSync(d).sort()) {
      const p = join(d, f);
      if (statSync(p).isDirectory()) walk(p);
      else out.push([relative(dir, p), readFileSync(p, "utf8")]);
    }
  };
  walk(dir);
  return out;
}

export function loadGalleryIndex(path = GALLERY_INDEX_PATH): GalleryEntry[] {
  if (!existsSync(path))
    throw new Error(`${path} not found; run scripts/llm-bench/make-gallery.ts`);
  return JSON.parse(readFileSync(path, "utf8"));
}

/**
 * The context named by `spec`. A `pack:` path is resolved from `from` (where
 * the command was typed), or from tests/llm-bench/ when it is not there.
 */
export function loadContext(spec: string, from: string): GofishContext {
  if (spec.startsWith("pack:")) {
    const p = spec.slice(5);
    const path = [resolve(from, p), resolve(BENCH_DIR, p)].find(existsSync);
    if (!path) throw new Error(`docs pack ${p} not found`);
    const text = readFileSync(path, "utf8");
    return {
      name: `pack:${basename(path)}`,
      sha256: hash([text]),
      systemText: text,
    };
  }
  if (spec === "cheatsheet" || spec === "retrieval") {
    const sheet = readFileSync(CHEATSHEET_PATH, "utf8");
    if (spec === "cheatsheet")
      return { name: spec, sha256: hash([sheet]), systemText: sheet };
    const indexText = readFileSync(GALLERY_INDEX_PATH, "utf8");
    const retriever = new Retriever(JSON.parse(indexText));
    return {
      name: spec,
      sha256: hash([sheet, indexText]),
      systemText: sheet,
      retrieve: (instruction) => retriever.top(instruction, 3),
    };
  }
  if (spec === "skill") {
    if (!existsSync(join(SKILL_DIR, "SKILL.md")))
      throw new Error(
        `${SKILL_DIR}/SKILL.md not found; run scripts/llm-bench/make-gallery.ts`
      );
    return {
      name: spec,
      sha256: hash(folderFiles(SKILL_DIR).flat()),
      systemText: SKILL_POINTER,
      skillDir: SKILL_DIR,
    };
  }
  throw new Error(
    `unknown context ${spec} (pack:<path>, cheatsheet, retrieval or skill)`
  );
}

/** The skill context's system text, after the arm prompt. */
export const SKILL_POINTER =
  "The GoFish skill is in ./ (read SKILL.md first). It is the only GoFish documentation you have. When you have what you need, reply with the program as described above.";

/** The retrieved examples, put before the task in the first user message. */
export function examplesMessage(examples: GalleryEntry[]): string {
  const blocks = examples.map(
    (e) =>
      `### ${e.title}\n\n${e.description}\n\n\`\`\`js\n${e.code.trimEnd()}\n\`\`\``
  );
  return (
    "Here are GoFish gallery examples that may be related to the task. They load their own data; your program uses the `data` argument described in the task.\n\n" +
    blocks.join("\n\n") +
    "\n\nThe task:"
  );
}

// ---------------------------------------------------------------------------
// Retrieval: BM25 over title, description and the code's identifiers
// ---------------------------------------------------------------------------

const STOP = new Set(
  `a an and are as at be by each for from has have in into is it its of on one or per so that the their them then there these this to use uses using with without which while where what when your you all any its not no only same than other its
  const let var function return import export default async await new true false null undefined document getelementbyid app container render chart data as any`
    .split(/\s+/)
    .filter(Boolean)
);

/** Light stemming so "bars" matches "bar" and "categories" "category". */
function stem(w: string): string {
  if (w.length > 4 && w.endsWith("ies")) return w.slice(0, -3) + "y";
  if (w.length > 3 && w.endsWith("s") && !w.endsWith("ss"))
    return w.slice(0, -1);
  return w;
}

/** Words of a text: camelCase and punctuation split, lowercased, stemmed,
 *  stopwords and one-letter words dropped. */
export function terms(text: string): string[] {
  return text
    .replace(/([a-z0-9])([A-Z])/g, "$1 $2")
    .toLowerCase()
    .split(/[^a-z0-9]+/)
    .filter((w) => w.length > 1 && !STOP.has(w) && !/^\d+$/.test(w))
    .map(stem);
}

/** The GoFish names a program imports (`spread`, `stack`, `clock`, ...).
 *  Other identifiers (data fields, local variables) say more about the
 *  example's dataset than about how it is built, so they are left out. */
function identifiers(code: string): string {
  const names: string[] = [];
  for (const m of code.matchAll(
    /import\s*\{([^}]*)\}\s*from\s*["']gofish-graphics["']/g
  ))
    for (const part of m[1].split(",")) names.push(part.trim().split(/\s+/)[0]);
  return names.filter(Boolean).join(" ");
}

/** Field weights: a title word counts three times, a description word
 *  twice, a code identifier once. */
function docTerms(e: GalleryEntry): string[] {
  const t = terms(e.title);
  const d = terms(e.description);
  return [...t, ...t, ...t, ...d, ...d, ...terms(identifiers(e.code))];
}

export class Retriever {
  private docs: { entry: GalleryEntry; tf: Map<string, number>; len: number }[];
  private df = new Map<string, number>();
  private avgLen: number;

  constructor(
    entries: GalleryEntry[],
    private k1 = 1.2,
    private b = 0.75
  ) {
    this.docs = entries.map((entry) => {
      const ts = docTerms(entry);
      const tf = new Map<string, number>();
      for (const t of ts) tf.set(t, (tf.get(t) ?? 0) + 1);
      for (const t of tf.keys()) this.df.set(t, (this.df.get(t) ?? 0) + 1);
      return { entry, tf, len: ts.length };
    });
    this.avgLen =
      this.docs.reduce((s, d) => s + d.len, 0) / Math.max(1, this.docs.length);
  }

  /** BM25 score of every document for the query, highest first; ties go
   *  to the smaller id, so the order is deterministic. */
  scores(query: string): { entry: GalleryEntry; score: number }[] {
    const q = [...new Set(terms(query))];
    const n = this.docs.length;
    return this.docs
      .map((d) => {
        let score = 0;
        for (const t of q) {
          const f = d.tf.get(t);
          if (!f) continue;
          const df = this.df.get(t)!;
          const idf = Math.log(1 + (n - df + 0.5) / (df + 0.5));
          score +=
            (idf * f * (this.k1 + 1)) /
            (f + this.k1 * (1 - this.b + (this.b * d.len) / this.avgLen));
        }
        return { entry: d.entry, score };
      })
      .sort(
        (a, b) => b.score - a.score || a.entry.id.localeCompare(b.entry.id)
      );
  }

  top(query: string, k: number): GalleryEntry[] {
    return this.scores(query)
      .slice(0, k)
      .map((s) => s.entry);
  }
}
